### ISSUE TITLE
 将主页风格改成  "Modernist theme"

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#1]
将主页风格改成  "Modernist theme" （在 settings里设置，现在主页文件是 readme.md. 所以，不要改动任何文件）
就象FORK工程那样 https://littleflute.github.io/Games/

**Comment by jeremyjia** [comment]
I have done this feature. Please verify it. 
Thanks
Jeremy

**Comment by littleflute** [comment]
well done.

**Comment by jeremyjia** [comment]
done

**Comment by jeremyjia** [comment]
done to change the theme to "Modernist"

**Comment by littleflute** [comment]
good.

**Comment by jeremyjia** [comment]
Sun Apr 03 2022 13:25:54 GMT+0800 (China Standard Time)

**Comment by jeremyjia** [comment]
Sun Apr 03 2022 13:27:58 GMT+0800 (China Standard Time)

**Comment by jeremyjia** [comment]
Sun Apr 03 2022 14:50:30 GMT+0800 (China Standard Time)

**Comment by jeremyjia** [comment]
Sun Apr 03 2022 14:53:29 GMT+0800 (China Standard Time)

**Comment by jeremyjia** [comment]
Sat Apr 09 2022 10:48:52 GMT+0800 (China Standard Time)

**Comment by jeremyjia** [comment]
Thu Apr 14 2022 17:30:45 GMT+0800 (China Standard Time)

**Comment by jeremyjia** [comment]
Thu Apr 14 2022 20:14:57 GMT+0800 (中国标准时间)

**Comment by jeremyjia** [comment]
https://www.runoob.com/
