### ISSUE TITLE
Hello输出

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#102]
在云环境下，用Linux C语言实现Hello world输出，作为一个测试

**Comment by jeremyjia** [comment]
1. ssh -F hp.cfg aws，远程登陆
2.建立一个文件夹jiapeng，在文件夹下新建一个文件hello.c
3.打开hello.c，编写如下代码
  #include <stdio.h>
  int main(){
    printf("hello world!");
}
4. 运行命令gcc -o hello hello.c编译代码  会有一个hello文件输出
6 运行程序 ./hello

**Comment by littleflute** [comment]
请你直接把你所说的方法，按如下方法操作一下：
1. 在github上建立一个新的库，并把你说的内容放到库里；
2. 在云端clone你新创建的repo.
3. 在云端编译好程序。
4. 然后我再到云端测试。

**Comment by jeremyjia** [comment]
已经创建好新库CProgramOnCloud，提交了测试源代码，并且在云端Clone, 编译完成。
现在您可以到云端对应的CProgramOnCloud目录下直接运行 ./hello

**Comment by littleflute** [comment]
good job.
