### ISSUE TITLE
The audio file 10.mp3 doesn't exist!

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#1087]
服务端错误：请检查剧本文件是否存在且书写正确. The audio file 10.mp3 doesn't exist!
错误原因定位：Java connection reset

- [x] 增强程序的健壮性，对错误message进行细化
- [x] 文件不存在的错误，是由于网络原因下载不成功导致的，应该在下载失败的时候抛出错误，这个错误在黄老师的机器比较容易重现，我们对程序进行增强，尝试用curl命令再次进行下载，仍失败最终会抛出错误
- [x] 修改之前发现的一些小的BUG，详细见下面的comments

**Comment by littleflute** [comment]
If rate greater than six，

**Comment by jeremyjia** [comment]
Could you provide test script?

**Comment by littleflute** [comment]
https://littleflute.github.io/gt1/mp3/j72_4_4.mp3

**Comment by jeremyjia** [comment]
{"request":{"version":"gc4BLS: bv0.15","width":498,"height":318,"music":"https://littleflute.github.io/gt1/mp3/j72_4_4.mp3","rate":"1","frames":[],"superObjects":[{"type":"javascript","frameRange":"(1,500)","attribute":{"script":"http://localhost:8080/firework.js","function":"animateFrame","start":1},"layer":1}]}}

**Comment by jeremyjia** [comment]
The rate 8.0 is large than the frame total times 5

**Comment by jeremyjia** [comment]
剧本没有frame的时候应该做到，目前可能存在问题
1. 背景音乐可以更换
2. 超级对象可以运行

**Comment by jeremyjia** [comment]
剧本没有frame的时候应该做到，目前可能存在问题
1. 背景音乐可以更换
2. 超级对象可以运行
