### ISSUE TITLE
create jpeg with linux C

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#109]
用Linux C编程实现保存一个JPEG图片

1. 在内存缓冲区Buffer中构造一幅测试图数据，这里为0～255渐变竖条纹，利用libgpeg库输出为jpeg图片。
2. 实现代码放在repository https://github.com/jeremyjia/CProgramOnCloud 下的jpegdemo目录
3. 其中主要实现代码见demo1.c

**Comment by jeremyjia** [comment]
测试步骤
1. go to repository CProgramOnCloud
2. go to folder jpegdemo
3. run ./makefile to compile project. demo1 program will be created
4. run ./demo1
5. will be output a file named "grayImage.jpg"

**Comment by jeremyjia** [comment]
![grayImage](https://user-images.githubusercontent.com/17973348/77851496-11add380-720c-11ea-8fc2-c9926cd9fd06.jpg)

**Comment by littleflute** [comment]
做的不错。
scp命令我还不知道是什么。
我这样看图：https://github.com/littleflute/CProgramOnCloud/blob/master/jpegdemo/grayImage.jpg
