### ISSUE TITLE
UI编辑器的宽高应该保持初始化的时候为偶数

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#1094]
需求：由于剧本的视频要求with,height为偶数，在UI编辑器的初始化的时候应保证宽高参数为偶数，
目前初始化的时候是手动进行拉框，不能保证偶数，后续还需要手动进行修改，不是很方便

**Comment by littleflute** [comment]
![mmexport1723238364127](https://github.com/user-attachments/assets/7a1e22d3-343b-413d-82b2-a32360119510)
