### ISSUE TITLE
Graphic drawing

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#111]
Linux C

#110, 已经实现了绘制一幅绿色竖条纹渐变图并保存为JPEG。这里进一步探索图形的绘制算法。
需求描述：
在内存缓冲区绘制圆，矩形，并保存成JPEG图片。
编写demo3.c实现此需求

**Comment by jeremyjia** [comment]
算法实现主要是根据平面直角坐标系下，数学曲线公式进行绘制，如到圆的定义，
到定点的距离等于定长的点的轨迹集合，(x-x0)^2+(y-y0)^2=R^2

**Comment by jeremyjia** [comment]
运行./demo3, 程序输出graphicImage.jpg，如下图

**Comment by jeremyjia** [comment]
![graphicImage](https://user-images.githubusercontent.com/17973348/77933794-c7972180-72e1-11ea-860a-fd9a1c3c3d52.jpg)

**Comment by littleflute** [comment]
1. 几何图形实现的不错。这是需需要的。
2. 在现有的基础上，能否在图上写字？a. 英语字母; b. 中文。

**Comment by jeremyjia** [comment]
理论上肯定是可以实现了，我们可能计算机图形学的功底不够深厚，实现起来困难一些

**Comment by littleflute** [comment]
1.你说的这写文字的方法，其实还是几何图形，你是在模拟一个真人写字。这是由人来决定写什么。
2. 一般电脑上说写字，应当是指将存在缓存里的字符串写到画布上，所谓的呈现或渲染（render)。在Window下这是可以实现的，HTML5上也可以实现，甚至可以用电脑上装有的不同字体写。

**Comment by jeremyjia** [comment]
我记得您讲过Windows 上的DC（Device Context），再借助TextOut函数就可以绘制文字。然后可以用大恒的那个IMAGE DLL把已经含有文字的数据存成JPEG文件。

Linux 上也应该有类似DC的概念，但我还没有去学习。。。我周日刚好看到了libgpeg这个开源的库，按照三步就可以生成一个JPEG文件。
1. 准备原始图像数据 （可从文件读取，或从摄像机等设备获取，或自己构造）
2. 将数据压缩（调用libgpeg API）
3. 将压缩后的数据写到文件（调用C语言的File API）

我这里的探索是在第一步上，利用数学知识直接在w*h*3的Buffer里构造出圆，矩形数据，再用后面2，3步骤将数据保存成JPEG。所以想在Buffer里直接构造一个汉字图形的数据还是有难度的。Windows上借助DC和相关的API来构造一帧数据是比较容易的，Linux上我还不知道怎么弄。

**Comment by littleflute** [comment]
1. 你经常做得很好了。
2. 写字功能应该是最后一个主要需求。其实，在大恒时我一直在思考这个问题。当时我就想做内核驱动的写字功能，直到我走时，也没机会做出来。不过，我一直在想这个问题。
3. 甚至想到了自己做字体库。从这个角度想的话，我最近做的那个中文输入法跟这个问题也有点关系。

**Comment by jeremyjia** [comment]
@littleflute 我找到一个Linux的库，应该是类似Windows的MFC，可以实现文字的叠加，我正在研究，我会另开一个ISSUE来跟进。。。

这个直接在内存Buffer里构建图形文字的思路我还会继续做，因为涉及到图形学的算法，比较有意思
