### ISSUE TITLE
Draw graphic and text with OpenCV

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#112]
Linux C 编程实现叠加文本和图形到JPG

OpenCV这个库功能非常强大，是用C++写的开源的计算机视觉库，支持多个平台。我基于它在Linux平台编写一个C++程序实现以下需求：

1. 打开一个src.jpg，是一张只有灰色背景的图片。获取到一个Image对象，绘制文本到这个对象上，绘制图形到这个对象上
2. 将Image对象保存为targe.jpg，该图片中包含上述叠加的文本和图形

**Comment by jeremyjia** [comment]
代码相见https://github.com/jeremyjia/CProgramOnCloud， opencvdemo

**Comment by jeremyjia** [comment]
![target](https://user-images.githubusercontent.com/17973348/78119066-6f276780-743a-11ea-8fc4-71fb9d8e4366.jpg)

**Comment by littleflute** [comment]
Good job!
