### ISSUE TITLE
能否提供完整的音频文件保存和播放代码示例

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#1128]
当然可以。下面是一个完整的示例，展示如何使用Web Audio API生成一个简单的和弦音频，将其保存为WAV文件，并提供一个按钮来播放生成的音频。这个示例使用了OfflineAudioContext进行音频渲染，Blob对象进行文件保存，并且包含了一个简单的WAV文件头写入函数。

首先，确保你的HTML文件中有一个按钮用于触发音频的生成和播放，并且已经引入了FileSaver.js库（你可以通过CDN或者本地引入）。

**Comment by littleflute** [comment]
这段代码做了以下几件事：

当按钮被点击时，generateAndSaveChord函数被调用。
generateChord函数生成一个简单的三和弦频率数组。
使用OfflineAudioContext渲染和弦音频到缓冲区。
在offlineContext.oncomplete回调中，将音频缓冲区转换为带有WAV文件头的Blob对象。
使用FileSaver.js将生成的WAV文件保存到用户的设备上。
可选地，将生成的音频URL设置到audio元素以供播放。
请注意，这个示例中的WAV文件头写入函数createWAVBlob是简化的，并且假设音频数据是单声道的16位PCM格式。如果你需要处理更复杂的音频格式或多声道，你可能需要更复杂的文件头写入逻辑。

**Comment by jeremyjia** [comment]
# 演示链接
https://jeremyjia.github.io/Games/issues/1128/
