### ISSUE TITLE
SpringBoot hello

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#117]
基于Java的SpringBoot技术，写一个hello world应用程序，部署到aws云端

**Comment by jeremyjia** [comment]
代码 https://github.com/jeremyjia/J2EE， Spring

**Comment by jeremyjia** [comment]
如果浏览器中显示以下文字，表示测试成功

Hello JeremyJia!

**Comment by littleflute** [comment]
good job.
