### ISSUE TITLE
Parameter validation for Clock Image Service

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#120]
#118 程序的服务接口为http://localhost:8080/image/clock?time=10:20:15 当输入参数非法时，程序应该抛出异常，例如time=a:0:0，time=25:61:0。。。应抛出输入的是一个无效的时间错误

**Comment by maomaof** [comment]
Please review and merge pull request #6 
https://github.com/maomaof/J2EE/pull/6

**Comment by jeremyjia** [comment]
Thanks maomaof, Good Job!
