### ISSUE TITLE
实现 119# 测试用例2 

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#121]
https://github.com/jeremyjia/Games/issues/119 
1. 建立一个 issues/121 目录.  做为本任务的工作目录。
2.  生成 .giignore 文件，实现只对生成的脚本做版本控制，运行脚本时生成的 图片和视频不要版本控制。可模仿 119#

**Comment by jeremyjia** [comment]
已完成此需求，脚本见 Games/issues/121。我在Mac OS上测试过，
@littleflute @maomaof 你们可在AWS上测试

Unix系统下测试方法（需要安装ffmpeg https://ffmpeg.org/download.html）：
1） 启动服务程序 java -jar pbz-demo-0.0.1-SNAPSHOT.jar，为测试方便，我放了一个在
      Games/issues/121目录下
2）到Games/issues/121 目录下，运行 ./r60.sh 生成 60张图，图片保存在output文件夹下面
3）到 Games/issues/121 目录下，运行 ./jpg2v.sh 360, 生成 vs60s.mp4。
4）到 Games\issues\121 目录下，运行 ./mp4i.sh 生成 index.html。
Notes：这里我优化了原mp4i.bat的代码，保留了脚本中的全部逻辑，生成的index.htm与Windows完全相同
5) 到Games/issues/121 目录下，运行 index.html, 在 网页上点 [v60s.mp4]铵钮，应看到播放效果
