### ISSUE TITLE
实现 119# 测试用例1， 写并推送一篇公众号文章

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#122]
https://github.com/jeremyjia/Games/issues/119

1. 同步自己库到 源库。 建立一个 issues/122 目录， 在此目录下运行测试流程，生成的图片和视频导入版本控制。
2. pull request 到源库，并 merge.
3. 文章内容：测试流程描述，插入生成的视频。

**Comment by maomaof** [comment]
运行index.html，在win7 上的chrome，firefox, IE 无法弹出播放器，win10 上edge, chrome, IE 都成功。

**Comment by jeremyjia** [comment]
I have merged your pull request. Below is the demo link:
https://jeremyjia.github.io/Games/issues/122/index.html

**Comment by maomaof** [comment]
公众号已发
