### ISSUE TITLE
编程实现：合并两张图片为一张

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#124]
1. 程序运行时，接受两大小一样的图片做为输入（设为 l0.jpg, r0.jpg，大小均为640*480)
2. 程序 运行结束，生成一张新图片（设为a0.jpg)。a0的左半部分是l0l0的左半部分，a0的右半部分是r0的右半部分）
![https://littleflute.github.io/diwo1/samples/l0.jpg](https://littleflute.github.io/diwo1/samples/l0.jpg)
![https://littleflute.github.io/diwo1/samples/r0.jpg](https://littleflute.github.io/diwo1/samples/r0.jpg)
![https://littleflute.github.io/diwo1/samples/all.jpg](https://littleflute.github.io/diwo1/samples/all.jpg)

**Comment by littleflute** [comment]
上面的实例图合并后可明显看出是拼的。往后看能不能做个模糊算法让其看不出来。这次先做简单的无失真合并。

**Comment by littleflute** [comment]
https://github.com/littleflute/diwo1/blob/master/samples/all.jpg
https://github.com/littleflute/diwo1/blob/master/samples/l0.jpg
https://github.com/littleflute/diwo1/blob/master/samples/r0.jpg

**Comment by jeremyjia** [comment]
基于Opencv实现此需求，代码见https://github.com/jeremyjia/CProgramOnCloud opencvdemo项目
测试步骤：
1. cd opencvdemo目录, 运行 ./makefile编译代码，会生成程序demo3
2. 运行 ./demo3 l0.jpg r0.jpg
3. 会生成一个stitch_all_image.jpg，即为合后的图片
