### ISSUE TITLE
[feature request] - Implement a searchPath demo with Javascript

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#13]
**我升级了一下，请完成这个：:btn1**

**1.create a branch for this feature. 
2. working in this branch to fulfill the feature.
3. when feature is done, make a Pull request to master branch.**

Implementation of a Javascript version demo of searchpath at home page "https://jeremyjia.github.io/Games/" when clicking a sub button next to d1

**Comment by littleflute** [comment]
Here is the test page:https://jeremyjia.github.io/Games/issues/4/c2Test.html

**Comment by jeremyjia** [comment]
好的，您太厉害了，我昨天晚上就是不知道怎么调用"blo0.blMDiv"这个接口。

**Comment by jeremyjia** [comment]
I have done this task and tested successfully with the above url. One more question, if i am working on a branch what url should i used for test?

**Comment by littleflute** [comment]
做得不错。
现阶段我的意思是让所有参与者对git的工作方式有一个大致一样的认识。最基本的一个思想是：每做一个任务都应该先创建一个分支，做完后Merge 到 Master分支（Pull request).
至于你现在这个任务，工作成果输出有两个地方：一是issue4#comment2#,二是https://jeremyjia.github.io/Games/issues/4/c2.js（这个是为了对工作内容有版本控制）.
这两个输出结果的测试方法说明如下：
issue4#comment2#的测试，在任何一个网站（源库或者Fork库）主页上的第2#Button 就是测试，所以需要把最终结果copy 到issue4#comment2#里面。
https://jeremyjia.github.io/Games/issues/4/c2.js的测试，做为开发者本人，在其工作电脑上，其工作目录下的c2Test.html就是其开发过程中的回归测试。如果想展示给别人看的话，在Merge到Mａｓｔｅｒ之后才可以。如果一定要展示给别人看的话，其实应该用第一个输出结果展示。
第二个输出结果主要是为了版本控制。

**Comment by littleflute** [comment]
![c2t1](https://user-images.githubusercontent.com/17950965/60752543-cbc52700-9f7b-11e9-9a33-350d8ead5b48.png)
如上图，1#->28#，算法能优化出绿箭头你线路就好了。

**Comment by jeremyjia** [comment]
![image](https://user-images.githubusercontent.com/17973348/61185835-3703ad00-a690-11e9-917a-32040fccbcb2.png)

增加BFS算法获取最短路径，绿色路线即为BFS算法获得的

**Comment by jeremyjia** [comment]
关于算法部分，我想先告一段落。未来我可能会增加A*算法，它是基于BFS做的改进，对目标节点有个估计函数，目的是减少盲目遍历的范围。很多游戏路径问题都在用A*算法...

接下来，可以考虑其他方面的需求，如编辑地图，选择算法，保存地图，加载地图等等
