### ISSUE TITLE
测试：生成 包含音频，字幕和图像的视频

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#132]
工作目录: [github\ffmpeg\issues\11]
最后把测试报告发公众号。

测试步骤如下：
0. r60.bat (start server first. ref: https://github.com/jeremyjia/Games/issues/129)
1. create v2.mp4 (j2v2.bat)
2. create srtv2.mp4 (psrt.bat)
3. create v3.mp4 (mkv3.bat)
4. mp4i.bat
5. index.html

 play v3.mp4 (should have video , audio, subtitle)

Bug : Time duration are different in video and audio)

**Comment by maomaof** [comment]
Done
