### ISSUE TITLE
升级 时钟图片生成程序（增加字幕功能）

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#133]
参考：https://github.com/jeremyjia/Games/issues/132
字幕输入为文本文件（*.srt), 现有实例文件 https://github.com/littleflute/ffmpeg/blob/master/issues/11/1.srt

**Comment by jeremyjia** [comment]
实现需求：
解析字幕文件，根据字幕的个数及每个字幕持续的秒数，生成若干张一秒一帧的JPG图片

**Comment by jeremyjia** [comment]
测试步骤：
1. 启动服务程序 java -jar pbz-demo-0.0.1-SNAPSHOT.jar, 在服务程序所在目录下放置字幕文件，    如1.srt
2. 允许命令curl http://localhost:8080/image/subtitle?filename=1.srt，或者在浏览器里输入http://localhost:8080/image/subtitle?filename=1.srt
3. 此时在服务程序所在目录下会生成若干JPG图片，1.jpg，2.jpg, 3.jpg...
4. 此时在浏览器里输入http://localhost:8080/1.jpg可显示图片，或者执行curl  http://localhost:8080/1.jpg -o 1.jpg可下载图片

**Comment by jeremyjia** [comment]
![12](https://user-images.githubusercontent.com/17973348/83889179-67a77600-a77d-11ea-869f-e5c655fd1458.jpg)

**Comment by jeremyjia** [comment]
http://localhost:8080/swagger-ui.html
