### ISSUE TITLE
字幕文件和音频文件参数可以来自URL所指定文件

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#143]
#140 中的参数目前只是服务器端的文件，它应该可以是URL指定的文件

测试用例1：（兼容性测试）

- [x] 启动服务程序 java -jar pbz-demo-1.0.10-SNAPSHOT.jar 
- [x] 浏览器运行： http://localhost:8080/image/combine?subtitlefile=1.srt&audiofile=1.mp3
- [x] 期待结果：将字幕文件和音频文件合成视频

测试用例2: （本次issue实现的功能测试）

- [x] 将测试用例1中的字幕文件1.srt和音频文件1.mp3换成URL的写法，例如
https://littleflute.github.io/cchess/xxx.srt
https://littleflute.github.io/cchess/xxx.mp3
可自行先上传一些标准的字幕和音频文件到repository中作为测试用例2的素材

**Comment by jeremyjia** [comment]
@waynexw 这个issue是我们在做剧本设计之前做的一个research，当时定的名字是combine接口

**Comment by jeremyjia** [comment]
最新的代码改动在 pull request #414

**Comment by littleflute** [comment]
http://localhost:8080/image/combine?subtitlefile=https://littleflute.github.io/english/NewConceptEnglish/Book2/1.lrc&audiofile=https://littleflute.github.io/english/NewConceptEnglish/Book2/1.mp3
