### ISSUE TITLE
在线编辑剧本功能

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#147]
想法： #144 中的剧本，实现剧本在线编辑，并立即演示视频效果
- [x] 显示文件列表 'http://localhost:8080/getResourceOnServer?filetype=json'
- [x] 运行shell命令 http://localhost:8080/command?cmd=cmd%2C%2Fc%2Cdir'
- [x] 画面大小可调
- [x] 坐标合理化
https://littleflute.github.io/J2EE/Spring/script/1.html

pr: https://github.com/maomaof/J2EE/pull/44
pr: https://github.com/maomaof/J2EE/pull/42
pr: https://github.com/maomaof/J2EE/pull/41
pr: https://github.com/maomaof/J2EE/pull/38
pr: https://github.com/maomaof/J2EE/pull/36
pr: https://github.com/maomaof/J2EE/pull/34

**Comment by littleflute** [comment]
ref: Executing Shell Commands with Node.js
https://stackabuse.com/executing-shell-commands-with-node-js/#:~:text=Conclusion-,Node.,be%20available%20via%20event%20listeners.
