### ISSUE TITLE
剧本生成程序

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#149]
参考 #144 #146中的剧本，写一个剧本的生成程序

**Comment by littleflute** [comment]
测试步骤：

编译生成服务程序mvn clean install
拷贝Script目录下的jpg2video.sh, 1.mp3, video.json到服务程序所在目录下
启动服务程序java -jar pbz-demo-0.0.1-SNAPSHOT.jar
在客户端浏览器中输入 http://localhost:8080/image/video?script=video.json
返回渲染的视频页面，可直接播放
注意：
可以用 http://localhost:8080/uploadpage 接口上传自己编辑好的剧本文件到服务器，如MyVideo.json
然后运行第四步的API http://localhost:8080/image/video?script=MyVideo.json 即可合成自己定义的视频
5. 返回渲染的视频页面, url:    
 http://localhost:8080/vFinal.mp4   
http://localhost:8080/vSubtitle.mp4
