### ISSUE TITLE
https://github.com/maomaof/J2EE  Spring项目前端升级

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#151]
1. 所有已经实现功能，可以从主页开始可以进行演示 （即有链接可前往演示）
   http://localhost:8080/
  包括swagger-ui链接。
2. http://localhost:8080/upload
   升级此API,当上传成功后，返回信息中，有返回主页的链接。
3. http://localhost:8080/image/video?script=video.json
    升级此API,,当操作成功后， ，返回信息中，有返回主页的链接。

参考 https://github.com/jeremyjia/Games/issues/144

**Comment by maomaof** [comment]
Done
