### ISSUE TITLE
https://github.com/maomaof/J2EE Spring项目后端升级

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#152]
https://github.com/maomaof/J2EE 
1. new Endpoint:
    以json格式作为输入，在后端保存为 json 文件。（之前已经有上传功能，但现在要的是一个新的API）
2. new Endpoint:  返回后端目录下所有的 mp3 文件（json格式：如 {"1.mp3","2.mp3",...}）
3. new Endpoint:  返回后端目录下所有的 jpg 文件（json格式：如 {"1.jpg","2.jpg",...}）
4. new Endpoint:  返回后端目录下所有的 json 文件（json格式：如 {"1.json","2.json",...}）
5. new Endpoint:  返回后端目录下所有的 png 文件（json格式：如 {"1.png ","2.png ",...}）
6. new Endpoint:  返回后端目录下所有的 mp4 文件（json格式：如 {"1.mp4 ","2.mp4 ",...}）
7. new Endpoint:  返回后端目录下所有的 gif 文件（json格式：如 {"1.gif ","2.gif ",...}）

**Comment by jeremyjia** [comment]
curl -H "Content-Type: application/json" -X POST  --data {\"userName\":\"Jeremy\",\"userID\":110} http://localhost:8080/json?filename=aa.json

**Comment by jeremyjia** [comment]
1. 新增接口调用，目的获取服务器端服务程序所在目录下的资源
    http://localhost:8080/getResourceOnServer?format=mp4
    返回：{"resource":["vFinal.mp4","vSubtitle.mp4"]}

**Comment by jeremyjia** [comment]
2
用curl命令测试新增接口
curl -H "Content-Type: application/json" -X POST  --data ‘{\\"userName\\":\\"Jeremy\\",\\"userID\\":110}’ http://localhost:8080/json?filename=aa.json

注意：JSON中的双引号要先转义\\"再发给后端，Ajax中的JSON.stringify可能就能做到
以下代码未经测试，仅供参考
var postURL = "http://localhost:8080/json?filename=aa.json";
$.ajax({
    url: postURL,
    data:encodeURIComponent(JSON.stringify(data.field)),
    type:"post",
    contentType: "application/json;charset=UTF-8", 
	dataType:"application/json;charset=UTF-8",
    success:function(data){
        //do somethings
    }
})

**Comment by jeremyjia** [comment]
Verified
