### ISSUE TITLE
剧本协议升级

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#153]
1. 增加 矢量 “直线” 角色 （起台，终点，颜色，厚度）
2. 增加 矢量 “矩形” 角色 （起台，终点，颜色）
3. 增加 矢量 “椭圆” 角色 （起台，终点，颜色）

**Comment by jeremyjia** [comment]
{
    "request": {
        "version": "0.0.3", 
        "width": 1024, 
        "height": 768, 
        "music": "1.mp3", 
        "rate": "1", 
        "frames": [
            {
                "number": "1", 
                "time": 5, 
                "objects": [
                    {
                        "graphic": "line", 
                        "attribute": {
                            "left": 100, 
                            "top": 100, 
                            "right": 100, 
                            "bottom": 300, 
                            "size": 5.5, 
                            "color": "255,0,255"
                        }
                    }, 
                    {
                        "graphic": "circle", 
                        "attribute": {
                            "left": 200, 
                            "top": 200, 
                            "width": 200, 
                            "height": 200, 
                            "color": "120,156,20"
                        }
                    }, 
                    {
                        "graphic": "rect", 
                        "attribute": {
                            "left": 500, 
                            "top": 400, 
                            "width": 100, 
                            "height": 150, 
                            "color": "142,28,124"
                        }
                    }
                ], 
                "backgroundColor": "100,100,100"
            }
        ]
    }
}

**Comment by jeremyjia** [comment]
<img width="700" alt="Screen Shot 2020-07-14 at 11 14 56 PM" src="https://user-images.githubusercontent.com/17973348/87443499-2b8eed00-c628-11ea-919c-7055ae4d4610.png">

**Comment by jeremyjia** [comment]
已提交修改：
https://github.com/maomaof/J2EE/pull/32
