### ISSUE TITLE
Permission denied and resource file not found

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#157]
服务程序启动后，应自动将所需脚本拷贝到当前目录下，并修改好执行权限
即，无需手动操作，就可以运行示例程序的剧本，生成视频

**Comment by jeremyjia** [comment]
代码已经提交到https://github.com/maomaof/J2EE

**Comment by littleflute** [comment]
代码已经提交,以后这样说: https://github.com/maomaof/J2EE/pull/26
