### ISSUE TITLE
server 能否将目录  script 设置为 http://localhost:8080/plx 

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#161]
如果可以的话，以下url将为返回 plx1.js的文本内容。
http://localhost:8080/plx/plx1.js

目的：方便前端开发，在开发时，文件直接可以版本控制。目前，开发过程中，版本控制有点迂回。

**Comment by jeremyjia** [comment]
1. 这个没办法做到，或者说很难做到，目前想受控新增加的文件，必须拷回到现有的Script目录下。。。

2. 有一个解决办法（不推荐），不再Target下启动服务程序，将它拷贝到工程目录下，即运行mvn的那个目录，在这个目录下建立plx目录并且受控于GitHub，这样能达到直接版本控制新增脚本的目的。并且能这样访问 http://localhost:8080/plx/plx1.js

3. 顺便提一下，可以在现有的script目录下新增任何的子文件夹，如plx文件夹，放置所需的脚本文件，当服务程序启动后，是可以 http://localhost:8080/plx/plx1.js 这样访问的，但无法做到直接受控，必须迂回受控
