### ISSUE TITLE
new Endpoint:  http://localhost:8080/download?url=...

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#162]
如下面的链接，将在服务器上生成文件 1.mp3
http://localhost:8080/download?url=https://littleflute.github.io/english/NewConceptEnglish/Book2/1.mp3
http://localhost:8080/download?url=https://littleflute.github.io/dvd1/027_1040/VTS_01_1%2000_00_00-00_05_10.mp4

**Comment by jeremyjia** [comment]
已提交 https://github.com/maomaof/J2EE/pull/29

**Comment by jeremyjia** [comment]
以下是我在MAC OS上测试结果：
{"pathOnServer":"/Users/jjia/Downloads/jiaJ2ee/J2EE/Spring/3.mp3","code":200,"filename":"3.mp3","message":"文件下载成功, 花费时间:15721ms"}

@littleflute 请黄老师在AWS上测试一下

**Comment by jeremyjia** [comment]
{"code":500,"message":"Server returned HTTP response code: 400 for URL: https://littleflute.github.io/dvd1/027_1040/VTS_01_1 00_00_00-00_05_10.mp4","reason-phrase":"Internal Server Error","exception-class":"java.io.IOException"}

**Comment by jeremyjia** [comment]
当下载URL 有空格的时候会有问题，以下提交用于修复这个小问题
https://github.com/maomaof/J2EE/pull/31

**Comment by jeremyjia** [comment]
Verified on AWS

{"pathOnServer":"/home/ubuntu/gh/jeremyjia/J2EE/Spring/target/VTS_01_1 00_00_00-00_05_10.mp4","code":200,"filename":"VTS_01_1 00_00_00-00_05_10.mp4","message":"文件下载成功, 花费时间:623ms"}
