### ISSUE TITLE
Endpoint : 运行服务器端命令

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#164]
命令例子：

- [ ]  ffmpeg -i v1.mp4 v2.mp4 //成功后，将生成 v2.mp4 (如果有 v1.mp4的话）
- [ ] mkdir dir1   //成功后，将生成 目录 dir1

**Comment by jeremyjia** [comment]
设计：
开放一个万能的接口，意思是可以执行任何一个Command：
调用格式
http://localhost:8080/command?cmd=参数1,参数2,参数3。。。

**Comment by jeremyjia** [comment]
Done: https://github.com/maomaof/J2EE/pull/33

**Comment by jeremyjia** [comment]
应该还是有BUG的，并不是什么命令都能执行成功
