### ISSUE TITLE
ffmpeg音频合成技术

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#167]
此ISSE用于总结一些ffmpeg音频合并的命令，作为日后需求的技术积累

- [x] 在视频的制定位置插入音频,ref:https://segmentfault.com/q/1010000021299139
- [x] https://github.com/littleflute/ffmpeg/issues/42

**Comment by jeremyjia** [comment]
混合音频叠加命令：
ffmpeg -i 1.mp3 -i 2.mp3 -filter_complex amix=inputs=2:duration=first:dropout_transition=2 out.mp3

**Comment by jeremyjia** [comment]
问题：
1. 怎么在拼接两个音频文件的时候，加入一些延迟，即Sleep一段时间？？？

**Comment by littleflute** [comment]
ref: https://superuser.com/questions/579008/add-1-second-of-silence-to-audio-through-ffmpeg
see: anull1.bat, anull2.bat  [under script folder]

**Comment by jeremyjia** [comment]
https://blog.csdn.net/qq_36270700/article/details/103278283?utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-1.control&dist_request_id=&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-1.control

**Comment by jeremyjia** [comment]
https://zhuanlan.zhihu.com/p/357885031

**Comment by littleflute** [comment]
- [ ] md issues/167
- [ ] create asserts file: A_Bass.wav, A_Sax.wav
- [ ] create null30s.bat : use to make 30 sec muted audio
- [ ] create insert.bat: use to make a audio at specific time(sec)
- [ ] create m2.bat: use to mix two audios.

Test case1:

- [ ] run        null30s.bat                                                                       : get null30s.mp3
- [ ] run        insert A_Bass.wav 0 null30s.mp3 xds0.mp3                     : get xds0.mp3
- [ ] run        insert A_Sax.wav 1 null30s.mp3 xds1.mp3                      : get xds1.mp3
- [ ] run        m2 xds0.mp3 xds1.mp3 xds_0-1.mp3                             : get xds_0-1.mp3
- [ ]  run       insert A_Bass.wav 2 null30s.mp3 xds2.mp3                     : get xds2.mp3
- [ ]  run        m2 xds2.mp3 xds_0-1.mp3 xds_0-2.mp3                       : get xds_0-2.mp3
- [ ] run       insert A_Bass.wav 3 null30s.mp3 xds3.mp3                     : get xds3.mp3
- [ ] run        m2 xds3.mp3 xds_0-2.mp3 xds_0-3.mp3                       : get xds_0-3.mp3
