### ISSUE TITLE
HTML5语音合成Speech Synthesis API

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#168]
无意中发现一个HTML 5的API可以语音播放一段给定的文字，现在用这个ISSUE记录一下

**Comment by jeremyjia** [comment]
var value = "hello, jeremy";
var utterThis = new window.SpeechSynthesisUtterance(value);
window.speechSynthesis.speak(utterThis);

**Comment by jeremyjia** [comment]
测试方法，将上面的代码粘贴到 https://jeremyjia.github.io/Games/ 3号上即可测试

**Comment by jeremyjia** [comment]
<img width="696" alt="Screen Shot 2020-07-19 at 5 41 32 PM" src="https://user-images.githubusercontent.com/17973348/87871931-31e5e600-c9e7-11ea-8d14-e93d86ac1e12.png">

**Comment by littleflute** [comment]
英语可以，中文好象不行，可能要安装中文模块才行

**Comment by jeremyjia** [comment]
var utterThis = new window.SpeechSynthesisUtterance();
utterThis.text = '您好，黄老师！';
utterThis.lang="zh";
window.speechSynthesis.speak(utterThis);

**Comment by jeremyjia** [comment]
Q：是否可以捕获这个API的音频流？以下链接或许能回答
https://github.com/guest271314/SpeechSynthesisRecorder
