### ISSUE TITLE
合成视频时，ffmpeg调用脚本中的视频分辨率应使用剧本中的分辨率

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#175]
这是一个BUG，此ISSUE修复这个问题

@maomaof , 请修改以下代码解决这个问题
JsonSriptParser.java
jpg2video.bat
jpg2video.sh

**Comment by maomaof** [comment]
Done
https://github.com/maomaof/J2EE/commit/10b3b510b8e4d2f2b4e91118366d6bac13fe122d
https://github.com/maomaof/J2EE/commit/d187059b5e32e24d663e67b75e39bbc9c634f30c
