### ISSUE TITLE
mvn clean install failed on AWS

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#182]
[ERROR] Failures: 
[ERROR]   VideoTest.TEST_combineSubtiteAndAudio2MP4:63 Cannot found srt file:test.srt
[ERROR]   VideoTest.TEST_generateVideoByscenario:120 Cannot found json file:scenario.json
[INFO] 
[ERROR] Tests run: 7, Failures: 2, Errors: 0, Skipped: 1
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.540 s
[INFO] Finished at: 2020-08-09T14:18:17Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project pbz-demo: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/ubuntu/gh/jeremyjia/J2EE/Spring/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]

**Comment by jeremyjia** [comment]
@maomaof 这个是测试用例导致的问题，请修复这个BUG

**Comment by jeremyjia** [comment]
@maomaof 
https://blog.csdn.net/dnc8371/article/details/106701188?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.channel_param&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.channel_param

**Comment by maomaof** [comment]
Done. Upgrade to Junit5.
https://github.com/maomaof/J2EE/commit/c8e6c9247abe2defbb9e6afbd212fab7cee437b9
