### ISSUE TITLE
http://localhost:8080/ 升级

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#183]
1. 加一个醒目的版本号
2. 加一个ID 为 "plx_p1_btn" 的 Button.
3. 加载 如下：javascript 文件

<script src="https://littleflute.github.io/JavaScript/w3.js" ></script> 
 <script src="https://littleflute.github.io/JavaScript/blclass.js" ></script>
 <script src="plx/p1.js"></script>

**Comment by maomaof** [comment]
Done
