### ISSUE TITLE
ref Game: 经典推箱子

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#190]
https://jeremyjia.github.io/Games/issues/190/

http://www.4399.com/flash/15332_4.htm
https://www.b4games.com/play-boxkid-game/play/
https://github.com/MoRanQingChen/pushBox

**Comment by jeremyjia** [comment]
推箱子游戏，我手上有以前收集的c++写的源码，和javascript写的部分主要代码(在一本网页游戏设计的书上)
