### ISSUE TITLE
基于Java应用WebSocket技术

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#194]
学习研究Java-WebSocket，实现Java版本的websocket client

**Comment by jeremyjia** [comment]
https://github.com/littleflute/JavaScript/pull/52

**Comment by jeremyjia** [comment]
测试方法：
1. CD到 https://github.com/littleflute/JavaScript 的i/49目录下
2. 启动服务程序: node index.js
3. CD到javaclient/build目录，启动Java Client程序：java -jar Demo.jar

**Comment by littleflute** [comment]
ubuntu@ip-172-31-25-127:~/gh/littleflute/JavaScript/i/49/javaclient$ java -jar Demo.jar
Error: Unable to access jarfile Demo.jar

**Comment by jeremyjia** [comment]
在~/gh/littleflute/JavaScript/i/49/javaclient目录下，
1. 运行 ant （编译工程的命令，类似于mvn）
2. 运行 java -jar build/Demo.jar

Demo.jar是编译生成的Client端可执行程序，在javaclient/build文件夹下

**Comment by littleflute** [comment]
@jeremyjia 
测试通过。
怎么把这个功能移植到 andriod  libgdx app 工程里。

**Comment by jeremyjia** [comment]
> @jeremyjia
> 测试通过。
> 怎么把这个功能移植到 andriod libgdx app 工程里?

这个交给我吧，开一个issue #199
