### ISSUE TITLE
websocket cpp client helloworld app 如何让 cpp1.cpp 编译通过？

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#195]
https://github.com/littleflute/JavaScript/blob/master/i/49/cppclient/cpp1.cpp
如何让 cpp1.cpp 编译通过？

代码参考自：https://stackoverflow.com/questions/34423092/websocket-library
头文件在此： https://github.com/Microsoft/cpprestsdk

**Comment by jeremyjia** [comment]
https://github.com/littleflute/JavaScript/pull/50

**Comment by jeremyjia** [comment]
chmod 755 makefile
./makefile

app1 是编译生成的可执行程序

**Comment by jeremyjia** [comment]
https://devblogs.microsoft.com/cppblog/c-rest-sdk-websocket-client/
