### ISSUE TITLE
java -jar pbz-demo-0.0.1-SNAPSHOT.jar --server.port=8081 运行，出现的 Bug

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#205]
http://localhost:8081/image/video?script=video.json
此用例需要升级：让以任意端口运行，都可播放视频。

**Comment by jeremyjia** [comment]
I have fixed this issue. Please use the code in Games/Spring

 java -Dserver.port=8081 -jar pbz-demo-0.0.1-SNAPSHOT.jar
