### ISSUE TITLE
blClass.js 使用教程

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#21]
https://mp.weixin.qq.com/s/4U5bMjaodmRaeGXZpop48A

**Comment by littleflute** [comment]
alert("i21c1");

**Comment by littleflute** [comment]
//blo0.blAjx(worker,url);  unit Test
var w = {};
w._2do = function(txt){
    alert(txt);
}
var urlLrc = "https://littleflute.github.io/english/NewConceptEnglish/Book2/1.lrc"
blo0.blAjx(w,urlLrc);

**Comment by jeremyjia** [comment]
var xmlHttpReg = null;
          if (window.ActiveXObject) {//If IE

              xmlHttpReg = new ActiveXObject("Microsoft.XMLHTTP");
			  alert(1);

          } else if (window.XMLHttpRequest) {

              xmlHttpReg = new XMLHttpRequest(); //实例化一个xmlHttpReg
			  alert(2);
          }

         var url = "https://api.github.com/repos/jeremyjia/Games/issues/comments/515761823?access_token=fbf22eeec3879587c82a8427d93cf682c13a2f89";		  
		  var data= {
		  "body": "Update a comment from API \n\n----Jeremyjia Updated1"
		  };
          if (xmlHttpReg != null) {
              xmlHttpReg.open("PATCH", url, true);
			  xmlHttpReg.send(JSON.stringify(data));
              xmlHttpReg.onreadystatechange = doResult; //CallBack function
          }else{
		  alert(3);
		  }

          function doResult() {         
              if (xmlHttpReg.readyState == 4) {//4代表执行完成                 
                 alert("OK "+xmlHttpReg.status);
                  if (xmlHttpReg.status == 200) {//200代表执行成功
                     var  msg = xmlHttpReg.responseText;
					 alert(msg);
                   }
              }

          }

**Comment by jeremyjia** [comment]
//i4c4
var s= "v0.0.27 "; 
s += "<a target='_blank' href='https://github.com/jeremyjia/Games/edit/master/issues/4/c4.js'"
s += " style='color:blue;'";		s +=">"; s += "c4.js* ";
s += "<a target='_blank' href='https://jeremyjia.github.io/Games/issues/4/c4.js'"
s += " style='color:green;'";		s +=">"; s += "c4.js ";
s += "<a target='_blank' href='https://jeremyjia.github.io/Games/issues/4/c4Test.html'"
s += " style='color:brown;'";		s +=">"; s += "c4Test.html";

var md = blo0.blDiv(document.body, "div_ID_4_I4C4", s ,blGrey[0]);  
if(!md.run){
    md.run = true; 
	var style ="position: absolute;";
	style += "z-index: 9;";
	style += "background-color: #f1f1f1;";
	style += "text-align: center;";
	style += "border: 1px solid #d3d3d3;";
	style += "left: 400px";
	style += "top: 40px";
	style += "width: 540px";
	md .style =style;
	
	var title = blo0.blDiv(md , "div_ID_4_I4C4" + "Header", "Header");
	style ="padding: 10px;";
	style += "z-index: 10;";
	style += "cursor: move;";
	style += "text-align: center;";
	style += "border: 1px solid #fff;";
	style += "background-color: #2196F3;";
	title.style =style;
 
    blo0.blMakeDivMovable(md );
	md.style.left = "400px";
	md.style.top = "40px";

	md.v = blo0.blDiv(md,md.id+"v","Let's chat!",blColor[1]);
	md.v.ta = blo0.blTextarea(md.v, md.v.id+"ta", "", blGrey[3]);
	md.v.ta.style.width="98%"; 
	md.v.ta.style.height="240px"; 
	
	md.v.ta1 = blo0.blTextarea(md.v, md.v.id+"ta1", "", blGrey[4]);
	md.v.ta1.style.width="90%"; 
	md.v.ta1.style.height="50px"; 
	
	md.v.btnSend = blo0.blBtn(md.v,md.v.id+"btnSend","Send/Read",blColor[4]);
	md.v.btnClear = blo0.blBtn(md.v,md.v.id+"btnClear","ClearMsg",blColor[4]);
	
	md.v.btnSend.onclick= function(){	
	   var s = md.v.ta1.value;
	   if(s!=""){
		 SendMsg(s);
	   }
	   md.v.ta1.value="";
	   //setTimeout("readMsg()", 1000)
	}
	md.v.btnClear.onclick= function(){
	   allMsg="";
       SendMsg("Let's chat");
       //setTimeout("readMsg()", 200)	   
	}
	
	 var timerId = setInterval(function()
	 {
	  readMsg();
	  md.v.ta.value = allMsg;
	 },1000);
	
	var allMsg="";
    readMsg();
	
	function SendMsg(ss){
		     var xmlHttpReg = null;
          if (window.ActiveXObject) {
             xmlHttpReg = new ActiveXObject("Microsoft.XMLHTTP");
	 } else if (window.XMLHttpRequest) {
              xmlHttpReg = new XMLHttpRequest(); 
         }

        var url = "https://api.github.com/repos/jeremyjia/Games/issues/comments/515761823?access_token="+getToken();
		var myMsg=allMsg;
		if(myMsg!=""){
			myMsg+="\n";
		}
		myMsg+=ss;
		var data= {
		"body": myMsg
		};
			  if (xmlHttpReg != null) {
				  xmlHttpReg.open("PATCH", url, true);    
			      xmlHttpReg.send(JSON.stringify(data));
				  xmlHttpReg.onreadystatechange = SendCallBack;
			  }else{
			  alert("xmlHttpRequest is null!");
		}

          function SendCallBack() {         
              if (xmlHttpReg.readyState == 4) {            
                  if (xmlHttpReg.status == 200) {
                   }else{
					   alert("Write:"+xmlHttpReg.status);
				   }
              }
         }
	}
		
	function readMsg() 
	{	
        var xmlHttpReg = null;
          if (window.ActiveXObject) {
             xmlHttpReg = new ActiveXObject("Microsoft.XMLHTTP");
	   } else if (window.XMLHttpRequest) {
              xmlHttpReg = new XMLHttpRequest(); 
         }
		 var url = "https://api.github.com/repos/jeremyjia/Games/issues/comments/515761823?access_token="+getToken();
			  if (xmlHttpReg != null) {
				  xmlHttpReg.open("GET", url, true);
				  xmlHttpReg.setRequestHeader('If-Modified-Since', '0');
				  xmlHttpReg.send(null);
				  xmlHttpReg.onreadystatechange = readCallBack; 
			}else{
			  alert("xmlHttpRequest is null!");
		 }

          function readCallBack() {         
              if (xmlHttpReg.readyState == 4) {            
                  if (xmlHttpReg.status == 200) {
					 var msg = JSON.parse(xmlHttpReg.responseText);
					 if(msg.body==null || msg.body==""){
						 allMsg ="";
					 }else
					   allMsg=msg.body;
                   }else{
					   alert("The status code:"+xmlHttpReg.status);
					   clearInterval(timerId);
				   }
              }
         }
	}
	
	function getToken(){		        
		return "65d796cd3a"+"29b4dbab37"+"c02624d6b6"+"651c61eedb";
	}

}
_on_off_div(this,md);

**Comment by littleflute** [comment]
var d= bl$("id_4_board");
alert(d.board.clickSquare);

**Comment by littleflute** [comment]
var d= bl$("id_4_Get");
var ta = bl$("id_4_ta_showMsg");
d.onclick = function(){
  var a = ta.value;
  var b = a.split("cc1:");
  var c = b[b.length-1];
  var d = c.split(";");
  var e = d[0]]; 
  alert(e);
}

**Comment by littleflute** [comment]
var d= bl$("id_4_Get");
var ta = bl$("id_4_ta_showMsg");
d.onclick = function(){
  var a = ta.value;
  var b = a.split("cc1:");
  var c = b[b.length-1]; 
  var d = c.split(";");
  var e = d[0];
  alert(e);
}

**Comment by littleflute** [comment]
voaUtil.draw = function(o,ctx){
    o.text(ctx,"_parentXD: " + Date(),50,180); 
var ta = bl$("id_ta_Page_Txt");
    o.text(ctx,ta.value,50,280); 

    var l = [1,2,3,4,5];
    for(i in l){
       o.rect(ctx,50 + i*55,350,50,50,"red");   
    }  
  }

**Comment by littleflute** [comment]
var d = blo0.blMD("id_1aaa", s,    300,100,500,400, "lightgreen"); 
d.v = blo0.blDiv(d,d.id+"v","v",blGrey[0]);
var x1 = {};
x1.txt = blo0.t;
x1.blrF1 = function(b,d){ 
 d.innerHTML =x1.txt;
 var links = d.getElementsByTagName( 'a' );
 var last = links.length;
  var list = {};

  // for each anchor...
  for (var i = 0; i < last; i++) {

    list[links[i].href] = i;
    
    //' - text=' + links[i].innerHTML + '<br>';

 }  
blo0.blShowObj2Div(d,links[0]);
}
blo0.blShowObj2Div(d.v,x1);
   
_on_off_div(null,d);

**Comment by littleflute** [comment]
var d = blo0.blMD("id_1aaa", s,    300,100,500,400, "lightgreen"); 
d.v = blo0.blDiv(d,d.id+"v","v",blGrey[0]);
var x= {}; 
x.blrF1 = function(b,d){ 
 var v1 = blo0.blDiv(d,"id_4_v1",blo0.blMakeScript(),blGrey[0]);
 var v2 = blo0.blDiv(d,d.id+"v2","v2","green"); 
}
x.blrTest = function(b,d){ 
 var ls = blo0.blTags(bl$("blrF1Div").innerHTML,"DIV"); 
 blo0.blShowObj2Div(d,ls);
}
blo0.blShowObj2Div(d.v,x);
   
_on_off_div(null,d);

**Comment by littleflute** [comment]
var d = blo0.blMD("id_1aaa", s,    300,100,500,400, "lightgreen"); 
d.v = blo0.blDiv(d,d.id+"v","v",blGrey[0]);
var x= {}; 


x.blrRecord = function(b,d){ 
 d.innerHTML = "a";
 var tb= blo0.blDiv(d,d.id+"tb","tb","gray");
 var ui = blo0.blDiv(d,d.id+"ui","ui","lightgreen");
 var lsBtn = [];
 var btnPlus = blo0.blBtn(tb,tb.id+"btnPlus ","+","gray");
 btnPlus .onclick = function(){
   var n = lsBtn.length;
   var btn = blo0.blBtn(tb,tb.id + "btn"+n,n,"lightgreen");
   btn.onclick = function(_this,_ls){
        return function(){
            ui.innerHTML = _this.id;
            blo0.blMarkBtnInList(_this,_ls,"red","grey");
        }
   }(btn,lsBtn);
   lsBtn .push(btn);
 }
}

blo0.blShowObj2Div(d.v,x);
   
_on_off_div(null,d);

**Comment by littleflute** [comment]
var d = blo0.blMD("id_1aaa", s,    300,100,500,400, "lightgreen"); 
d.v = blo0.blDiv(d,d.id+"v","v","white"); 

function CX(_name){
   this.version = "v0.5";
   this.name = _name;

   this.blrGetDate = function(b,d){ 
      d.innerHTML = Date();
   }

   this.blrTest = function(b,d){ 
      var toolBar = blo0.blDiv(d,d.id+"toolBar","toolBar","lightgreen"); 
      var ui= blo0.blDiv(d,d.id+"ui","ui",blColor[0]); 
      var btnPlus= blo0.blBtn(toolBar,toolBar.id + "btnPlus", "+","skyblue"); 
      var btnDel= blo0.blBtn(toolBar,toolBar.id + "btnDel", "-","skyblue"); 
      var ls = [];


      btnPlus.onclick = function(){
           var n = ls.length;
           var btn= blo0.blBtn(toolBar,toolBar.id + "btn" + n, n,"gray");
           
           btn.onclick = function(_btn){
              return function(){ 
                  blo0.blMarkBtnInList(_btn,ls,"yellow","grey");              
              }
           }(btn);

ls.push(btn);
    }
   }
}
var x1= new CX("x1"); 

blo0.blShowObj2Div(d.v,x1); 
   
_on_off_div(null,d);

**Comment by littleflute** [comment]
asdfasdfasdf

**Comment by littleflute** [comment]
blo0.blScript("id_script_i655_index","issues/655/index.js");
//alert(blo0.blScript);

**Comment by littleflute** [comment]
var s = "test-server.js: v0. 11";
var d = blo0.blMD("id_4-"+s, s,    300,100,500,400, "lightgreen"); 
d.v = blo0.blDiv(d,d.id+"v","v",blGrey[0]);
var x= {}; 

x.blrTest = function(b,d){  
    f1(d);
   _on_off_div(b,d); 
   b.style.background = b.style.background=="red"?blGrey[5]:blColor[4];
}


blo0.blShowObj2Div(d.v,x);
bl$("blrTest").click();
_on_off_div(null,d);
 

function f1(d){
  getOnlineUser(function(j){
     blo0.blShowObj2Div(d,j);
});
}

**Comment by littleflute** [comment]
Q:5,, 1, 2, 3, | 5

**Comment by littleflute** [comment]
var s = "test-server.js: v0. 11";
var d = blo0.blMD("id_4-"+s, s,    300,100,500,400, "lightgreen"); 
d.v = blo0.blDiv(d,d.id+"v","v",blGrey[0]);
var x= {}; 
var ta = blo0.blGetTa();

x.blr_jeremyjia_Games_issues = function(b,d){ jgis(d); on(b,d);}; x.bll1j = "";
x.blr_getOnlineUser       = function(b,d){ f1(d); on(b,d);}; x.bll1 = "";
x.blr_addNewGitHubComment = function(b,d){ f2(d); on(b,d);}; x.bll2 = "";

x.blrGetGhi = function(b,d){
  x.i =  blo0.blGetGithubIssueByNumber("jeremyjia","Games",1,function(o){
       d.innerHTML = o.comments + blo0.blDate(); 
      
  }); 
}

x.blrGetGhiCs = function(b,d){
   d.innerHTML = blo0.blDate();
   x.i.cs(function(o){
      var tb1 = blo0.blDiv(d,d.id+"tb1","tb1","grey");
      var tb2 = blo0.blDiv(d,d.id+"tb2","tb2","lightblue");
      for(j in o){
          const btn = blo0.blBtn(tb1,tb1.id+j,j,"gray");
          btn .onclick = function(_j){
             return function(){
                 ta.value = o[_j].body;
             }
          }(j);
          const btn2 = blo0.blBtn(tb2,tb2.id+j,j,"green");
          btn2.cid = o[j].id;
          btn2 .onclick = function(_btn2,_j){
             return function(){
                 var testD = ta.value;
                 blo0.blUpdateGithubCommentById("jeremyjia","Games",_btn2.cid,testD,function(res){
                   ta.value = _btn2.cid;
                 });
             }
          }(btn2,j);
      }
   });
}
blo0.blShowObj2Div(d.v,x);
bl$("blr_jeremyjia_Games_issues").click();
bl$("blr_getOnlineUser").click();
_on_off_div(null,d);
 

function jgis(d){
  var tb = blo0.blDiv(d,d.id+"tb","tb",blGrey[0]);
  var tbx2  = blo0.blDiv(d,d.id+"tbx2","tbx2",blGrey[3]);
  var v1  = blo0.blDiv(d,d.id+"v1","v1",blGrey[4]);
  const isStart = ["11-101","11-120","71-80","81-90","91-99"];   

  for(i in isStart){
     var btn = blo0.blBtn(tb,tb.id+i,isStart [i] ,blGrey[1]);
     btn.onclick = function(_thisBtn,_i){
        return function(){
            var a = isStart[_i].split('-');
            tbx2.innerHTML = a; 
            for(var j = a[0]; j <= a[1];j++){
                var btn = blo0.blBtn(tbx2,tbx2.id+j,j ,blGrey[5]);
                btn.onclick = function(_j){
                  return function(){
                    v1.innerHTML = _j;
                  }
                }(j);
            }             
        }
     }(btn,i);
  } 
}
function f2(d){
    var ja = Date();
    addNewGitHubComment(1,ja,function(response){                            
                    if (response.readyState == 4) {
                        if (response.status == 200 || response.status == 201) {
                            d.innerHTML = Date();
                        } else {
                            d.innerHTML = "Errors, status=" + response.status;
                        }
                    }
    }); 
}

function f1(d){
  getOnlineUser(function(j){
     blo0.blShowObj2Div(d,j);
  });
}
function on(b,d){
   _on_off_div(b,d); 
   b.style.background = b.style.background=="red"?blGrey[5]:blColor[4];
}

**Comment by jeremyjia** [comment]
#============================以下为描述头定义==========================
V: 1.0
B: 同一首歌
Z: 陈哲 胡迎节  词
Z: 孟卫东 曲
Z: 李炳富 编合唱
D: E
P: 4/4
J: 深情地
#============================以下开始简谱主体==========================
Q: 5,, - 1 2 | 3. 4/ 3 1 | 2 - 1 6, | 1 - - - | 5, - 1 2 | 3 3/ 4/ 5 1 |
C: 鲜花曾告诉我你怎样走过，大地知道你心中的
C: 水千条山万座我们曾走过，每一次相逢和笑脸
Q: 4. 3/ 5 (2/ 3/) | 2 - - - | 3 - 5 1' | 7 - 6 - | 5 5/ 6/ 7 (6/ 5/) | 3 - - - |
C: 每一个角@落，甜蜜的梦啊谁都不会错@过，
C: 都彼~此铭@@刻，在阳光灿烂欢乐的日子@里，
Q1: 4. 4/ 5 6 | (5 4/ 3/) 2 - | 7, 7,/ 6,/ (5, 6,) | 1 - - - |&sbf 1' - 6 - | 4. 5/ 6 - |
C1: 终于迎来今@@天，这欢聚时@刻。星光洒满了
C1: 我们手拉手@@呀想说的太@多。阳光想渗透
Q2: 8 8 8 8 |* 8 8 8 8 |* 8 8 8 8 |* 8 8 8 8 |* 0 1 4 - | 6 - - 4/ 3/ |
C2: @@@@@@@@@@@@@@@@@星光洒满了
C2: @@@@@@@@@@@@@@@@@阳光想渗透

Q1: 7 7/ 7/ (7 6/ 5/) | 3 - - - | 1' - 6 - | 4. 5/ 6 - | 6, 6,/ 6,/ (6[5] 4/# 3/) | 2 - - - |
C1:所有的童@@年，风雨走遍了世间的角@@落}
C1:所有的语@@言，春天把友好故事@传@@说
Q2: 2 - - 1/ 2/ | 3 5 - - | 0 1 4 - | 6 - - 6/ 5/ | 4# - - 2/ 3/ | 5 5 - - |
C2:  所有的童年，@风雨走遍了世间的角落}
C2: 所有的语言，@春天把友好故事@传说
Q1: 5, - 1 2 | (3. 4/) 3 1/ 1/ | 2. 2/ 2 2/ 1/ | 6, 6, - - | 7, - 7, 6 | (5, 6) 5 2/ 2/ |
C2:同样的感@受给了我们同样的渴望，同样的欢@乐给了
Q2:  (3, - - 2 | 1) - - - | (6 - - 5 | 4) - - - | (5 - - 4 | 2) - - - |
C2:   啊@@啊@@啊
Q1: 4. 4/ 4 3/ 2/ |[++"1." 1 - - - :|][++"2." 5 - - - | {dsb 1 - 6 - | 4. 5/ 6 - | 7 7/ 7/ (7 6/ 5/) } 6 - 4 - |]/ 2. 3/ 4 - | 5 5/ 5/ (4 3/ 2/) |
C2:我们同一首歌。歌。阳光想渗透所有的语
Q2:  (2 - - - | 3) - - - ( :|| 3) - - - | 0 1 4 - | 6 - - 4/ 3/ | 2 - - 1/ 2/ |
C2:  啊@@@阳光想渗透所有的
[fenye]
Q1: 3 - - - | 1' - 6 - | 4. 5/ 6 6 | 6,. 6,/ (6[5] 4/# 3/) | 2 - - - | 5, - 1 2 |
Q2: 1 - - - | 6 - 4 - | 2. 3/ 4 4 | 6,. 6,/ (2 2/ 1/) | 7, - - - | 5, - 1 2 |
C2: 言，春天把友好的故事传@@说，同样的
Q3: 3 5 - - | 0 1 4 - | 6 - - 6/ 5/ | 4# - - (2/ 3/) | 5 5 - - | (3 - - 2 |
C3: 语言，@春天把友好的故事传说，啊


Q1:  (3. 4/) 3 1/ 1/ | 2. 2/ 2 2/ 1/ | 6, 6, - - | 7, - 7,. 6,/ | (5, 6) 5&hx 2/ 2/ | 4. 4/ 4 3/ 2/ |
Q2:  (3. 4/) 3 1/ 1/ | 2. 2/ 2 2/ 1/ | 6, 6, - - | 7, - 7,. 6,/ | (5, 6) 7, 7,/ 7,/ | 2. 2/ 2 1/ 7,/ |
C2: 感@受给了我们同样的渴望，同样的欢@乐给了我们同一首
Q3: 1) - - - | 6 - - 5 | 4 - - - | 5 - - 4 | 2 - - - | (2 - - - |
C3: @啊@@啊@@啊

Q1:  |/ {dsb 1 - - - | } 1 - - - | 6 - - - | 1' - - 1' | (1' - - - | 1') - - - ||
C1: 歌，同一首歌。
Q2:  |/ 3) - - - | 4 - - - | 3$ - - 3 | (3 - - - | 3) - - - ||
C2:

**Comment by jeremyjia** [comment]
{"request":{"version":"0.0.16","description":"LRC字幕超级对象","width":1024,"height":768,"music":"https://files.51voa.cn/202111/nasa-prepares-to-launch-asteroid-defense-test-mission.mp3","rate":"1","frames":[{"number":"1","time":"${VAR_TIME}","objects":[{"text":"${VAR_TITLE}","x":100,"y":300,"size":60,"color":"70,130,120","layer":2}],"backgroundColor":"200,200,222"}],"superObjects":[{"type":"subtitle","frameRange":"(1,${VAR_TIME})","attribute":{"script":"${VAR_LRC_PATH}","x1":20,"y1":670,"size":30,"color":"20,82,190"},"layer":1},{"type":"picture","attribute":{"x1":100,"y1":200,"x2":510,"y2":380,"size":50,"color":"255,0,0","name":"https://img.51voa.cn/1/C501D07B-81C5-462A-89C8-E630C2DD9A1F_w268_r1.jpg"},"frameRange":"(1,${VAR_TIME})","action":{"trace":"y=0*x*x+0*x+200","step":0}}],"Macros":[{"name":"VAR_TITLE","value":"字幕超级对象-演示程序"},{"name":"VAR_LRC_PATH","value":"https://www.51voa.com/lrc/202111/nasa-prepares-to-launch-asteroid-defense-test-mission.lrc"}]}}

**Comment by jeremyjia** [comment]
<svg width="1000" height="1415" version="1.1" viewBox="0 0 1000 1415" encoding="UTF-8" xmlns="http://www.w3.org/2000/svg">
<rect x="0" y="0" height="100%" width="100%" fill="#1fafff"></rect>

<defs>
<g id="shuzi_c_1" transform="translate(-50,-50)"><rect height="17.9" width="11.1" y="41.05" x="44.45" stroke-width="0" fill="#ffffff"></rect><path fill="black" d="m51.71225,56.72592c0,0.80306 0.32822,1.2029 0.98409,1.2029l1.85934,0l0,0.98408l-8.96846,0l0,-0.98408l1.74994,0c0.65642,-0.07163 0.98409,-0.43763 0.98409,-1.0935l0,-12.24893c-1.16737,0.65644 -2.26085,1.13125 -3.28105,1.42172l-0.43762,-0.76528c2.18699,-1.09351 4.04689,-2.47802 5.57743,-4.15573l1.53112,0l0,15.63882l0.00111,0l0.00001,0z"></path></g><g id="shuzi_c_2" transform="translate(-50,-50)"><rect height="17.9" width="11.1" y="41.05" x="44.45" stroke-width="0" fill="#ffffff"></rect><path fill="black" d="m44.23404,57.96309c0.29169,-0.36531 0.73117,-0.84104 1.31789,-1.42776c4.61288,-4.68482 6.66194,-7.8705 6.15051,-9.55537c-0.07361,-2.34241 -1.0262,-3.55098 -2.85551,-3.6246c-1.68486,0.14779 -2.74564,1.20857 -3.18512,3.18512l-1.09814,0c0.58504,-3.51473 2.45228,-5.34404 5.60115,-5.49184c3.07526,0.21974 4.72275,1.86723 4.9425,4.94249c0.14612,1.90516 -1.13607,3.99158 -3.84435,6.26038c-1.61124,1.46568 -2.85551,2.70996 -3.73447,3.73448l5.27211,0c1.24426,0.07362 1.93918,-0.6213 2.08697,-2.08698l0.8784,0l-0.54879,5.05236l-10.98313,0l0,-0.98827z"></path></g>

<g id="xiaojiexian_weibu" transform="translate(-50,-50)">
<rect fill="#1fffff" stroke-width="0" x="45.05" y="35.85" width="9.9" height="28.4"></rect>
<rect height="29" width="1.5" y="35.5" x="49.25" stroke-width="null" fill="#ffff1f">
</rect></g>


<g id="bl_lianYinXian" transform="translate(-50,-50)">
  <path d="M 84,114 C 90.5,104,100.5,104,107,114 M 107,114 C  
  100.5,105,90.5,105,84,114" stroke-width="0.5" stroke="#1b1bfb"></path>
</g>

</defs>

<use x="51" y="51" xlink:href="#bl_lianYinXian" xmlns:xlink="http://www.w3.org/1999/xlink"></use>

<use x="83" y="130" xlink:href="#shuzi_c_1" time="0.5" audio="1" notepos="0_1_1" code="1(/" xmlns:xlink="http://www.w3.org/1999/xlink"></use>

<use x="108" y="130" xlink:href="#shuzi_c_2" time="0.5" audio="2" notepos="0_1_2" code="2/)" xmlns:xlink="http://www.w3.org/1999/xlink"></use>

<use x="143" y="130" xlink:href="#xiaojiexian_weibu" notepos="0_1_3" time="0" audio="" code="|w" xmlns:xlink="http://www.w3.org/1999/xlink"></use>

<line x1="77" y1="143" x2="114" y2="143" data-type="jianshixian" stroke-width="2" stroke="#1b1b1b"></line>

<path d="M 84,114 C 90.5,104,100.5,104,107,114 M 107,114 C  100.5,105,90.5,105,84,114" stroke-width="0.5" stroke="#fb1b1b"></path> 

 </svg>

**Comment by jeremyjia** [comment]
#============================以下为描述头定义==========================
V: 1.0
B: 同一首歌
Z: 陈哲 胡迎节  词
Z: 孟卫东 曲
Z: 李炳富 编合唱
D: E
P: 4/4
J: 深情地
#============================以下开始简谱主体==========================
Q: 5,, - 1 2 | 3. 4/ 3 1 | 2 - 1 6, | 1 - - - | 5, - 1 2 | 3 3/ 4/ 5 1 |
C: 鲜花曾告诉我你怎样走过，大地知道你心中的
C: 水千条山万座我们曾走过，每一次相逢和笑脸
Q: 4. 3/ 5 (2/ 3/) | 2 - - - | 3 - 5 1' | 7 - 6 - | 5 5/ 6/ 7 (6/ 5/) | 3 - - - |
C: 每一个角@落，甜蜜的梦啊谁都不会错@过，
C: 都彼~此铭@@刻，在阳光灿烂欢乐的日子@里，
Q1: 4. 4/ 5 6 | (5 4/ 3/) 2 - | 7, 7,/ 6,/ (5, 6,) | 1 - - - |&sbf 1' - 6 - | 4. 5/ 6 - |
C1: 终于迎来今@@天，这欢聚时@刻。星光洒满了
C1: 我们手拉手@@呀想说的太@多。阳光想渗透
Q2: 8 8 8 8 |* 8 8 8 8 |* 8 8 8 8 |* 8 8 8 8 |* 0 1 4 - | 6 - - 4/ 3/ |
C2: @@@@@@@@@@@@@@@@@星光洒满了
C2: @@@@@@@@@@@@@@@@@阳光想渗透

Q1: 7 7/ 7/ (7 6/ 5/) | 3 - - - | 1' - 6 - | 4. 5/ 6 - | 6, 6,/ 6,/ (6[5] 4/# 3/) | 2 - - - |
C1:所有的童@@年，风雨走遍了世间的角@@落}
C1:所有的语@@言，春天把友好故事@传@@说
Q2: 2 - - 1/ 2/ | 3 5 - - | 0 1 4 - | 6 - - 6/ 5/ | 4# - - 2/ 3/ | 5 5 - - |
C2:  所有的童年，@风雨走遍了世间的角落}
C2: 所有的语言，@春天把友好故事@传说
Q1: 5, - 1 2 | (3. 4/) 3 1/ 1/ | 2. 2/ 2 2/ 1/ | 6, 6, - - | 7, - 7, 6 | (5, 6) 5 2/ 2/ |
C2:同样的感@受给了我们同样的渴望，同样的欢@乐给了
Q2:  (3, - - 2 | 1) - - - | (6 - - 5 | 4) - - - | (5 - - 4 | 2) - - - |
C2:   啊@@啊@@啊
Q1: 4. 4/ 4 3/ 2/ |[++"1." 1 - - - :|][++"2." 5 - - - | {dsb 1 - 6 - | 4. 5/ 6 - | 7 7/ 7/ (7 6/ 5/) } 6 - 4 - |]/ 2. 3/ 4 - | 5 5/ 5/ (4 3/ 2/) |
C2:我们同一首歌。歌。阳光想渗透所有的语
Q2:  (2 - - - | 3) - - - ( :|| 3) - - - | 0 1 4 - | 6 - - 4/ 3/ | 2 - - 1/ 2/ |
C2:  啊@@@阳光想渗透所有的
[fenye]
Q1: 3 - - - | 1' - 6 - | 4. 5/ 6 6 | 6,. 6,/ (6[5] 4/# 3/) | 2 - - - | 5, - 1 2 |
Q2: 1 - - - | 6 - 4 - | 2. 3/ 4 4 | 6,. 6,/ (2 2/ 1/) | 7, - - - | 5, - 1 2 |
C2: 言，春天把友好的故事传@@说，同样的
Q3: 3 5 - - | 0 1 4 - | 6 - - 6/ 5/ | 4# - - (2/ 3/) | 5 5 - - | (3 - - 2 |
C3: 语言，@春天把友好的故事传说，啊


Q1:  (3. 4/) 3 1/ 1/ | 2. 2/ 2 2/ 1/ | 6, 6, - - | 7, - 7,. 6,/ | (5, 6) 5&hx 2/ 2/ | 4. 4/ 4 3/ 2/ |
Q2:  (3. 4/) 3 1/ 1/ | 2. 2/ 2 2/ 1/ | 6, 6, - - | 7, - 7,. 6,/ | (5, 6) 7, 7,/ 7,/ | 2. 2/ 2 1/ 7,/ |
C2: 感@受给了我们同样的渴望，同样的欢@乐给了我们同一首
Q3: 1) - - - | 6 - - 5 | 4 - - - | 5 - - 4 | 2 - - - | (2 - - - |
C3: @啊@@啊@@啊

Q1:  |/ {dsb 1 - - - | } 1 - - - | 6 - - - | 1' - - 1' | (1' - - - | 1') - - - ||
C1: 歌，同一首歌。
Q2:  |/ 3) - - - | 4 - - - | 3$ - - 3 | (3 - - - | 3) - - - ||
C2:

**Comment by jeremyjia** [comment]
function(){
  alert(5);
}

**Comment by littleflute** [comment]
const tb = bl$("tb_4_AutoRun");
const v = bl$("vTask");
const o = tb.getObj();
const t = blo0.blTask();
const svrAPI = "http://localhost:8080/download";
const srcURL = "https://www.51voa.com/";
const fn = "51voa_" + blo0.blDate() +".txt";
var i = blo0.blDownloadTask(svrAPI ,srcURL,fn,v); 
t.setInfo(i);
o.addTask(t);

**Comment by jeremyjia** [comment]
var utterThis = new window.SpeechSynthesisUtterance();
utterThis.text = '你好，世界！';
window.speechSynthesis.speak(utterThis);
