### ISSUE TITLE
https://littleflute.github.io/AS-IT-IS/spider.html

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#210]
- [x] auto download .html .mp3 http://localhost:3000/  &  https://littleflute.github.io/vle202104/node/public/index.html
- [x] prev step .html + .mp3 to generate .mp4 (end point update + unit test in swagger UI)
- [x] https://littleflute.github.io/AS-IT-IS/spiter.html
- [x] sequelize (mysql)
- [x] https://github.com/littleflute/vle202104/issues/1

#265 
http://localhost:8080/image/video?script=video8.json
http://localhost:8080/video8.json

server: https://github.com/littleflute/JavaScript/issues/49

**Comment by jeremyjia** [comment]
https://github.com/jeremyjia/Games/issues/211

**Comment by jeremyjia** [comment]
Please see the design of #257
