### ISSUE TITLE
根据VOA的文本和音频URL地址生成视频

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#252]
此ISSUE用于细化#210；

**Comment by jeremyjia** [comment]
http://localhost:8080/image/voa?texturl=https://jeremyjia.github.io/Games/issues/210/asa1.html&audiourl=https://jeremyjia.github.io/Games/issues/210/as20210213a1.mp3

**Comment by littleflute** [comment]
http://localhost:8080/image/voa?texturl=https://learningenglish.voanews.com/a/us-passes-500-000-covid-19-deaths/5788231.html&audiourl=https://av.voanews.com/clips/VLE/2021/02/22/d0971641-dbf5-42ad-a0c3-481648efe62f.mp3?download=1

**Comment by jeremyjia** [comment]
我猜我明白您download=1的意思，程序已经考虑到了这种情况，如果Server上已经有了音频文件，程序不去下载。。。
需要在调用这个endpoint之前把d0971641-dbf5-42ad-a0c3-481648efe62f.mp3考到pbz-demo-0.0.1-SNAPSHOT.jar的同级目录下，以保证http://localhost:8080/d0971641-dbf5-42ad-a0c3-481648efe62f.mp3能访问到；
此时调用以下的两个命令中的任意一个都可以

http://localhost:8080/image/voa?texturl=https://learningenglish.voanews.com/a/us-passes-500-000-covid-19-deaths/5788231.html&audiourl=http://localhost:8080/d0971641-dbf5-42ad-a0c3-481648efe62f.mp3

http://localhost:8080/image/voa?texturl=https://learningenglish.voanews.com/a/us-passes-500-000-covid-19-deaths/5788231.html&audiourl=d0971641-dbf5-42ad-a0c3-481648efe62f.mp3

**Comment by littleflute** [comment]
@jeremyjia 我没有这个意思，上面只是我运行的一个测试，是直接从voa源测试的,通过了。这个功能你实现的不错。
往后会建立新的issue来规范一下这个end point. 这个issue我直接关了。

**Comment by jeremyjia** [comment]
<html>
<head>
<title>诗词赏析 枯树赋</title>
</head>
<body>

<p>昔年种柳, 依依汉南\n</p>
<p>今看摇落, 凄怆江潭\n</p>
<p>树犹如此, 人何以堪</p>

</body>
</html>
