### ISSUE TITLE
帧穿越对象可以播放动画，动画算法以插件的形式提供

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#255]
这是一个想法先记录下来，怎么设计可以再思考。。。

初步设想，以插件的形式提供动画算法供剧本文件调用
比如，剧本文件中定义一个对象，在第10帧到第20帧调用一个烟花效果的算法。

这里说的插件可以是一个JS文件，里面定义一个关于时间的动画算法函数

**Comment by jeremyjia** [comment]
ref:
https://github.com/littleflute/stats.js/blob/master/examples/custom.html

**Comment by jeremyjia** [comment]
设计实现这个想法：

启动服务程序后，可以运行下面这个链接，这是算法的HTML展示
http://localhost:8080/pluginCall.html

运行以下剧本实例，可以看到与上面HTML同样效果的视频，因为程序解析了Javascript提供的算法函数
http://localhost:8080/image/video?script=video10.json

**Comment by jeremyjia** [comment]
<img width="765" alt="截屏2021-04-01 下午11 13 18" src="https://user-images.githubusercontent.com/17973348/113315468-e63e5700-933f-11eb-8d16-1da5c37bcc8a.png">

**Comment by littleflute** [comment]
https://user-images.githubusercontent.com/17950965/113351451-c1ba8e80-92ef-11eb-8e81-c8d3be1fef0d.mp4
