### ISSUE TITLE
3x3Game Android update

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#26]
now it's V0.1.2. update to V0.1.3
 你的之前的任务我关闭了，建立一个新的任务，我升级了test工程，你可以在我这个版本上再升级一下。

说明：
1 初始时，随机开局。
2 Mouse 点空格边的数字格子，两者交换。
3. 当出现如下图所示情况时，结束获胜。
![t1](https://user-images.githubusercontent.com/17950965/60754197-7fd1ac80-9f92-11e9-94ea-e21d37097439.png)
升级需要完成任务：
美工，将目录（Games\gdx\test\android\assets）下所有（1，2，3，4，5，6，7，8）图片统一修改成一样的。
其他需求可根据自己想到的加。
** 先从master分支建立一个新的分支。我升级时的分支还在，你可以看到（3x3Game).在你建立的分支上工作，当你完成时,再 merge 到 master 分支上。

**Comment by littleflute** [comment]
![t1](https://user-images.githubusercontent.com/17950965/60754197-7fd1ac80-9f92-11e9-94ea-e21d37097439.png)

**Comment by jeremyjia** [comment]
我提一个需求，给这个游戏增加AI智能算法，能够自动的一步一步移动格子，知道目标数字出现

**Comment by jeremyjia** [comment]
![p](https://user-images.githubusercontent.com/17973348/60866914-28666180-a25c-11e9-81b1-8fa800dd9fad.jpeg)

**Comment by littleflute** [comment]
AI智能算法,我一开始就想要这个功能，但我没思路，你可以试试实现。
另外，这个游戏我有一个问题：如果一开始时如下图所示，是否有解？
如果无解，每次开局初始化就要确保其为有解。

**Comment by jeremyjia** [comment]
AI问题，我们下来再研究...
先说一下关于有无解的问题，有人做过这么一个结论：“如果这个拼图序列中存在的逆序数为偶数，那么这个拼图可以被还原到正确的顺序，如果不为偶数，那么不能被正确还原”. 
上图中，逆序数为1个（8>7）, 所以根据这个定律，此图无解。关于这个定律的证明，需要进一步理解和研究。

**Comment by jeremyjia** [comment]
关于这个定律，我目前的想法是逆向思维，我们从一个成功的界面开始，任意去玩，每走一步，我们看看是不是都符合“逆序数”为偶数，这样至少能感性认识一下上面的这个定律

**Comment by jeremyjia** [comment]
Reopen this issue to make sure there is a solution for the Initialization
