### ISSUE TITLE
根据剧本生成GIF动画图片

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#261]
- [x] 将命令集成到代码，
- [ ] 将参数设置放到剧本

**Comment by jeremyjia** [comment]
主要命令：
fmpeg -i vFinal.mp4 vFinal.gif
fmpeg -i vFinal.mp4 -ss 3 -t 10 vFinal.gif（设计截取的时间起始点和时长）

**Comment by littleflute** [comment]
ref: https://www.w3schools.com/graphics/tryit.asp?filename=trygame_image_background_loop
