### ISSUE TITLE
upgrade : http://localhost:8080/image/video?script=https://littleflute.github.io/vle202103/03/01/as20210301a1.json

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#265]
- [x] http://localhost:8080/image/video?script=https://littleflute.github.io/vle202103/03/01/as20210301a1.json to create a video
- [x] if local folder has the same file (as20210301a1.json), it should not be replaced.  （此需求的意思是：必须用url指定的文件生成视频，但是，如果本地目录有同名文件，这个文件还必须保留）
- [ ] 有个问题： http://localhost:8080/image/video?script=https://littleflute.github.io/vle202103/03/01/as20210301a2.json , 这个剧本生成的视频中，想让这个褐色的矩形覆盖滚动的文本，现在的剧本版本能做到吗？如果不能，就需要升级。
![image](https://user-images.githubusercontent.com/17950965/110915190-2b84e100-82cc-11eb-9cbb-99b25f0a3ef1.png)

**Comment by jeremyjia** [comment]
OK, I will implement this feature.

**Comment by jeremyjia** [comment]
please review the fixed pull request below:

https://github.com/jeremyjia/Games/pull/266

**Comment by jeremyjia** [comment]
@littleflute Please review code: https://github.com/jeremyjia/Games/pull/267

**Comment by jeremyjia** [comment]
<img width="704" alt="截屏2021-03-12 下午9 54 20" src="https://user-images.githubusercontent.com/17973348/110954628-ac52e400-8383-11eb-8d52-05ca764635b7.png">

**Comment by littleflute** [comment]
http://localhost:8080/image/video?script=https://littleflute.github.io/vle202103/03/01/ac20210301a1.json

**Comment by jeremyjia** [comment]
pull request again for this issue.

demo is:
http://localhost:8080/image/video?script=video8.json

<img width="711" alt="截屏2021-03-20 下午3 33 10" src="https://user-images.githubusercontent.com/17973348/111862661-a798bc00-8991-11eb-93cc-e1c55a28545e.png">

**Comment by jeremyjia** [comment]
verified
