### ISSUE TITLE
显示不正确？ http://localhost:8080/bli.html （ branch: i210)

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#284]
在分支 i210  下， 新建文件 bli.html，bls1.json, p1.js. 
无法显示：http://localhost:8080/bli.html

**Comment by littleflute** [comment]
我把p1.js 改名成 myplx1.js, 可以了。好像它优先 选择 plx/p1.js

**Comment by littleflute** [comment]
http://localhost:8080/image/video?script=bls2.json

**Comment by littleflute** [comment]
http://localhost:8080/myplx2.js    
从swagger ui 上传 myplx2.js “+” 会丢失

**Comment by littleflute** [comment]
http://localhost:8080/bls1.json

**Comment by littleflute** [comment]
https://user-images.githubusercontent.com/17950965/113701466-0ac26800-968d-11eb-83b8-2473decd0542.mp4

**Comment by littleflute** [comment]
http://localhost:8080/myplx2.js    
从swagger ui 上传 myplx2.js “+” 会丢失 （以.json接口上传）

**Comment by jeremyjia** [comment]
> plx/p1.js

是的，主程序启动后会把script，script/plx目录下的文件全部拷贝到主程序当前目录下作为资源文件

**Comment by littleflute** [comment]
Ok
