### ISSUE TITLE
handle this "Pull requests"

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#3]
https://github.com/jeremyjia/Games/pull/2

**Comment by jeremyjia** [comment]
Merged your pull request.

**Comment by jeremyjia** [comment]
blo0.blScript("id_script_codemirror","https://codemirror.net/codemirror.js");

**Comment by jeremyjia** [comment]
var d = blo0.blMD("id_4_codemirror_test", s,    300,100,100,400, "lightgreen"); 
d.v = blo0.blDiv(d,d.id+"v","v",blGrey[0]);
var x= {}; 


x.blrTest = function(b,d){ 
  const v = blo0.blDiv(d,"xdeditor","blue"); 
}
x.blrTest2 = function(b,d){
  xdtest1(d);
}

blo0.blShowObj2Div(d.v,x);
   
_on_off_div(null,d);
