### ISSUE TITLE
for: id_div_4_User_plx #4

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#303]
<!DOCTYPE html>
<html>
<title>Welcome</title>

<body>
  <h1>Welcome to the Page</h1>
  <p>Hello World</p>
  <img src="html5.gif" alt="HTML5" style="width:480px;height:300px">
</body>

</html>

**Comment by jeremyjia** [comment]
说明：这个issue号分配给waynexw使用，可以在这里定制自己的主页内容

#96 (主页上插件的总入口)
#95 （Jeremyjia）
#98 （littleflute）
#99   （xiyu）
#303 （waynexw）

**Comment by jeremyjia** [comment]
@waynexw
1. 同步一下主页的代码，参考，https://blog.csdn.net/GMingZhou/article/details/78790332
2. 把你fork的主页的链接改为：https://waynexw.github.io/Games
3. 如果上面的操作成功，应该能看到“欢迎来到waynexw的项目主页”
    可以编辑修改上面的HTML代码来定制自己的主页啦

**Comment by waynexw** [comment]
Finished

**Comment by jeremyjia** [comment]
<!DOCTYPE html>
<html>
<title>Welcome</title>
<body>
  <h1>&emsp; Welcome to W Page</h1>
  <!--<img src="html5.gif" alt="HTML5" style="width:480px;height:300px">--!>
  <!--<p>&emsp; &nbsp; Liu Li Chang (The Distributing Centre of Coloured Glaze) </p>--!>
 &emsp; &nbsp; <img id="scream" width="400" height="279" src="https://github.com/waynexw/Games/blob/master/img/png/llc.jpg?raw=true" hidden="true" alt="Liu Li Chang"/>

<canvas id="myCanvas" width="400" height="279" style="border:1px solid #d3d3d3;">
Your browser does not support the HTML5 canvas tag.
</canvas>

<script id="id_script">
    var canvas = document.getElementById("myCanvas");
    var ctx = canvas.getContext("2d");
    var img = document.getElementById("scream");
    img.src = "https://raw.githubusercontent.com/waynexw/Games/master/img/png/llc.jpg";
    img.onload=function(){
       ctx.drawImage(img, 0, 0, img.width, img.height);
       ctx.fillStyle = "yellow";
       ctx.font = "50px Arial";
       ctx.fillText("Happy Days",10,img.height*0.382);
   };

</script>
<p></p>
<p> &emsp; &nbsp; Useful Website: <a href="https://www.w3schools.com/">w3schools.com</a>, <a href="https://www.runoob.com/">runoob.com</a></p>
&emsp; &nbsp; <a href="https://github.com/waynexw/Download-n-backup/ ">'Download and Backup' Project</a>

<h4>&emsp; &nbsp;The Current Time: <script>var myDate = new Date(); document.write(myDate.toLocaleString())</script></h4>

<script>var myDate = new Date(); document.write(myDate.toLocaleString())</script>

<div <p>&emsp; &nbsp; Go to the Swagger page: <a href=http://localhost:5000/swagger/>Swagger</a></p></div>

&emsp; &nbsp;Parameter 1: <input type="text" name="p1" />
&emsp; &nbsp;Parameter 2: <input type="text" name="p2" />
&emsp; &nbsp; <input type="submit" value="Submit" />

<script id="id_script">
      var img = new Image();
      var selectedValue = 1;
       img.src = "http://silveiraneto.net/wp-content/uploads/2011/06/forest.png";
       var time = 0;
        var fun = function () {
             if(selectedValue == 1 ){
                  animateFrame(time++);
             }else{
                  animateFrame2(time++);
             }           
        }
        setInterval(fun, 100);
    
function animateFrame(time) {
    var canvas = document.getElementById('myCanvas');
    var ctx = canvas.getContext('2d');
    ctx.clearRect(0, 0, 2048, 1536);
       ctx.drawImage(img, 0, 0, img.width, img.height);
       ctx.fillStyle = "yellow";
       ctx.font = "40px Arial";
       var x1 = (time+200)%img.width;
       ctx.fillText("动画演示!", x1, img.height/2);
       ctx.fillStyle = "Blue";
       ctx.fillRect(10, 10, 100, 100);
      ctx.fillStyle = "Red";
      for (var i = 0; i < 2000; i++) {
          var x = Math.cos(time + i * 0.01) * 196 + 256;
          var y = Math.sin(time + i * 0.01234) * 196 + 256;
          ctx.beginPath();
          ctx.arc(x, y, 5, 0, Math.PI * 2, true);
          ctx.fill();
      }
}
function animateFrame2(time) {
    var canvas = document.getElementById('myCanvas');
    var ctx = canvas.getContext('2d');
    ctx.clearRect(0, 0, 2048, 1536);
       ctx.fillStyle = "red";
       ctx.font = "40px Arial";
       var x1 = (time+200)%img.width;
       ctx.fillText("动画演示!", x1, img.height/2);
       ctx.fillStyle = "yellow"; 
      var y1 = (time+200)%img.height;
       ctx.fillRect(30, y1, 60, 60);
       var myDate = new Date();
       var strTime = myDate.toLocaleString();
       ctx.fillStyle = "Blue";
       ctx.fillText(strTime, 10, img.height/3);
}
var selectObj = document.getElementById('sel');
selectObj.onchange = function(){
          var sel = document.getElementById('sel');
          var len = sel.options.length;
            for(var i=0;i<len;i++){
                if (sel.options[i].selected) {
                    selectedValue = sel.options[i].value;
                }
            }
}
</script>

</body>

</html>
