### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#304]
bug: 
http://localhost:8080/download?url=https://learningenglish.voanews.com/z/3521&filename=as.htm

Response Body
{
  "error": "The url https://learningenglish.voanews.com/z/3521 is not correct!"
}

ok:
http://localhost:8080/download?url=https://learningenglish.voanews.com/a/thai-villagers-feel-effects-of-mekong-river-dams/5860157.html&filename=as1a.htm

**Comment by littleflute** [comment]
在国内测试，需要科学上网。

**Comment by jeremyjia** [comment]
这是一个BUG.

如果不着急解决的话，我想让xiyu或者wangxu来该这个BUG.

**Comment by waynexw** [comment]
> 这是一个BUG.
> 
> 如果不着急解决的话，我想让xiyu或者wangxu来该这个BUG.

很愿意处理这个bug，不过我不知道如何上手。这个VOA的页面我能够打开，但bug这一行的链接 我打不开。

**Comment by littleflute** [comment]
@jeremyjia  @waynexw  可以约个时间进行一个 work session. 讨论解决一下这个问题。

**Comment by jeremyjia** [comment]
fixed it
