### ISSUE TITLE
rainDrop: branch test

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#31]
checkout rainDrop branch.
run gdx/test.
程序运行成功后，截个图，贴到这里来。

**Comment by xiyufeng** [comment]
![image](https://user-images.githubusercontent.com/52185614/61465512-c53aa480-a9aa-11e9-8af3-86ed5f4004a3.png)

**Comment by xiyufeng** [comment]
![rain](https://user-images.githubusercontent.com/52185614/61465673-19458900-a9ab-11e9-862e-aa7f02a0b50d.PNG)
