### ISSUE TITLE
Html5 canvas

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#311]
@waynexw 有时间可以学习一下HTML5 Canvas绘图技术，一方面将来可以为我们的项目写一些动画插件（这是我们目前一个有意思的设计, 我会详细介绍），另一方面也可以复习一下前端开发的基础知识，完善你的主页内容

可以参考下面的文档学习/复习

https://www.w3school.com.cn/html/html5_canvas.asp

**Comment by waynexw** [comment]
> @waynexw 有时间可以学习一下HTML5 Canvas绘图技术，一方面将来可以为我们的项目写一些动画插件（这是我们目前一个有意思的设计, 我会详细介绍），另一方面也可以复习一下前端开发的基础知识，完善你的主页内容
> 
> 可以参考下面的文档学习/复习
> 
> https://www.w3school.com.cn/html/html5_canvas.asp

我按照这篇文章，实际操作了最后一个实例（放置一幅图像在我的主页），但是最后完成效果不佳，只显示了一张图片，我感觉script和canvas的代码好像并没有执行，我核对了一下代码，没发现什么异常。请 @jeremyjia 有空儿时帮我看看 #303 ，多谢！

**Comment by jeremyjia** [comment]
@waynexw 做得不错！这个是我们原来设计上的一个不足，被你发现啦，我完善了一下代码，让总的调用处可以加载运行script标签下的代码。
并且把你写的代码做了一点点调整，现在功能上应该是好了，你可以看一下，可以继续做一些练习 :-)
