### ISSUE TITLE
新建一个github库(repo)，用于自动化下载备份voa网站的一个专题栏目（WORDS AND THEIR STORIES）

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#318]
目的：用于自动化下载备份voa网站的一个专题栏目（WORDS AND THEIR STORIES: https://learningenglish.voanews.com/z/987)

- [x] 新建一个github库(repo), 库名根据用途随便起一个名字。
- [x] 建好的库上建立库主页。
- [x] 在自己的项目主页上建立一个链接,可以链接到新建库的主页。自己的项目主页：https://waynexw.github.io/Games/
- [x] 上传r.jar文件到新建库的根目录下。r.jar在此： https://github.com/jeremyjia/Games/releases/download/i307/r.jar

**Comment by waynexw** [comment]
> * 上传r.jar文件到新建库的根目录下。

请教黄老师，这项任务我有点问题。我现在只会用网页上传文件，在上传r.jar文件时，说文件超过25M 不能上传。我现阶段只上传了一个小文件hello.py到新建库的根目录下。请您指教，谢谢。
