### ISSUE TITLE
python-flask-server-generated(swagger)

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#332]
- [x] fork : https://github.com/Sean-Bradley/Seans-Python3-Flask-Rest-Boilerplate ( https://www.youtube.com/watch?v=iZ2Tah3IxQc)
- [x] try to run it.
- [x] copy it to our repo(jeremyjia/Games)

test steps:

- [x]  go to folder [python/i7321]
- [x] 参考原始库的 说明 运行程序。
- [x] server 启动正常的话，可访问  http://127.0.0.1:5000/swagger/
- [x] http://localhost:5000/swagger/

**Comment by littleflute** [comment]
https://github.com/littleflute/swagger-samples/tree/master/python/python-flask-server-generated

**Comment by littleflute** [comment]
You7:04 PM
https://github.com/swagger-api/swagger-codegen/tree/master/samples/server/petstore/flaskConnexion
pip3 install -r requirements.txt
python3 -m swagger_server
Nes Cohen7:09 PM
werkzeug
Nes Cohen7:14 PM
virtualenv
pip3 install virtualenv
Nes Cohen7:17 PM
bin/activate
source test/bin/activate

**Comment by waynexw** [comment]
> * [x]  fork : https://github.com/Sean-Bradley/Seans-Python3-Flask-Rest-Boilerplate ( https://www.youtube.com/watch?v=iZ2Tah3IxQc)
> * [ ]  try to run it.
> * [ ]  copy it to our repo(jeremyjia/Games)

@littleflute 任务汇报如下：
fork完成。我把文件下载到本地运行，按照步骤先运行pip install -r requirements.txt   
报错信息：ERROR: Could not install packages due to an OSError: [WinError 2] 系统找不到指定的文件。: 'c:\\python39\\Scripts\\flask.exe' -> 'c:\\python39\\Scripts\\flask.exe.deleteme'
于是先pip install flask，后再执行pip install -r requirements.txt  仍然报错，信息同上。
如不理报错信息 继续执行python app.py，报错并无法启动服务。
等有时间我会继续研究一下pip命令的报错信息。

**Comment by littleflute** [comment]
@waynexw 先做第3项 copy it to our repo(jeremyjia/Games)

**Comment by littleflute** [comment]
Hosted Locally http://127.0.0.1:5000/swagger/

**Comment by jeremyjia** [comment]
在我的环境可以运行成功：

<img width="1409" alt="截屏2021-05-21 下午5 10 29" src="https://user-images.githubusercontent.com/17973348/119113402-a51d1600-ba57-11eb-9948-7e5ae52e9efa.png">

**Comment by waynexw** [comment]
@littleflute @jeremyjia 
现在我的环境可以正常显示http://127.0.0.1:5000/swagger/，错误排查如下：
卸载了现有版本的python3.7和3.9，重新安装了python 3.9.5，再运行相关命令，服务器启动正常，网页显示正常。
