### ISSUE TITLE
ffmpeg installment

### ISSUE THREAD

**Issue by waynexw** [jeremyjia/Games#337]
- [x] ffmpeg installment 

- [x] local host 8080 on website, and test on http://localhost:8080/image/video?script=video.json

**Comment by littleflute** [comment]
- [ ] ffmpeg -version

**Comment by waynexw** [comment]
请教一下，我已经安装并配置好了ffmpeg，ffmpeg -version 命令也显示正常。在本地成功运行r.jar文件，http://localhost:8080显示无问题，网页上一共四个功能，第一第二个功能无问题，第三个功能Video Generator，单击进入，有信息如下“服务端错误 请检查剧本文件是否存在且书写正确. video.json”   @jeremyjia  我不太清楚是哪里出问题了。

**Comment by littleflute** [comment]
> 请教一下，我已经安装并配置好了ffmpeg，ffmpeg -version 命令也显示正常。在本地成功运行r.jar文件，[http://localhost:8080显示无问题，网页上一共四个功能，第一第二个功能无问题，第三个功能Video](http://localhost:8080%E6%98%BE%E7%A4%BA%E6%97%A0%E9%97%AE%E9%A2%98%EF%BC%8C%E7%BD%91%E9%A1%B5%E4%B8%8A%E4%B8%80%E5%85%B1%E5%9B%9B%E4%B8%AA%E5%8A%9F%E8%83%BD%EF%BC%8C%E7%AC%AC%E4%B8%80%E7%AC%AC%E4%BA%8C%E4%B8%AA%E5%8A%9F%E8%83%BD%E6%97%A0%E9%97%AE%E9%A2%98%EF%BC%8C%E7%AC%AC%E4%B8%89%E4%B8%AA%E5%8A%9F%E8%83%BDVideo) Generator，单击进入，有信息如下“服务端错误 请检查剧本文件是否存在且书写正确. video.json” @jeremyjia 我不太清楚是哪里出问题了。

不要运行r.jar,运行 Spring/target 下的 .jar文件

**Comment by waynexw** [comment]
> > 请教一下，我已经安装并配置好了ffmpeg，ffmpeg -version 命令也显示正常。在本地成功运行r.jar文件，[http://localhost:8080显示无问题，网页上一共四个功能，第一第二个功能无问题，第三个功能Video](http://localhost:8080%E6%98%BE%E7%A4%BA%E6%97%A0%E9%97%AE%E9%A2%98%EF%BC%8C%E7%BD%91%E9%A1%B5%E4%B8%8A%E4%B8%80%E5%85%B1%E5%9B%9B%E4%B8%AA%E5%8A%9F%E8%83%BD%EF%BC%8C%E7%AC%AC%E4%B8%80%E7%AC%AC%E4%BA%8C%E4%B8%AA%E5%8A%9F%E8%83%BD%E6%97%A0%E9%97%AE%E9%A2%98%EF%BC%8C%E7%AC%AC%E4%B8%89%E4%B8%AA%E5%8A%9F%E8%83%BDVideo) Generator，单击进入，有信息如下“服务端错误 请检查剧本文件是否存在且书写正确. video.json” @jeremyjia 我不太清楚是哪里出问题了。
> 
> 不要运行r.jar,运行 Spring/target 下的 .jar文件，可参考 #341

 @littleflute  谢谢黄老师  已经测试成功。输出结果为一段合成的视频，音频内容为一段新概念英语 A Private Conversation，视频为此音频的同步字幕。
