### ISSUE TITLE
bug: canvas 的 moveto lineto 可能还没实现 （bli.html, bls1.json 表现不一样)

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#341]
- [x] test steps (master branch):
- [x] mvn clean install -DskipTests
- [x]  java -jar pbz-demo-1.0.3-SNAPSHOT.jar
- [x] http://localhost:8080/bli.html
- [x] http://localhost:8080/image/video?script=bls1.json

**Comment by jeremyjia** [comment]
https://github.com/jeremyjia/Games/pull/353
