### ISSUE TITLE
Python实现抓取网站的页面内容

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#343]
#322 已经搭建起一个简单的Python服务器，并返回一个hello字符串。现在要升级这个程序，
让它返回更有实际意义的内容，这里我暂定是某个网页的页面内容，通过这个练习可以学习用Python爬取数据的基本方法

**Comment by jeremyjia** [comment]
可以参考如下代码

import urllib.request
url = 'http://news.baidu.com/sports'
#创建request对象
req = urllib.request.Request(url)
#发送请求，获取结果
with urllib.request.urlopen(req) as response:
    data = response.read()
    content = data.decode()
    print(content)

**Comment by waynexw** [comment]
> 可以参考如下代码
> 
> import urllib.request
> url = 'http://news.baidu.com/sports'
> #创建request对象
> req = urllib.request.Request(url)
> #发送请求，获取结果
> with urllib.request.urlopen(req) as response:
> data = response.read()
> content = data.decode()
> print(content)

@jeremyjia 不好意思，我记忆太差了，忘了怎样开启python服务器。
基于此任务，我已经完成的步骤是：
1. git pull  把本库games文件夹下的内容，下载到我计算机上
2. 在我计算机本地python目录下新建了一个文件new server.py  其内容为上面的代码。
3. 按我的理解，现在我应该在本地运行new server.py来启动服务器，但是我实在想不起来 应该怎么运行这个py的文件，也或者我以上步骤实际是错误的？
请指教，多谢。

**Comment by jeremyjia** [comment]
hello waynexw ：
1.一般文件名最好不要含有空格，可以叫new_server.py这样的名字
2. 用python new_server.py或者python3 new_server.py运行python代码
3. 如果你拷贝我上面的代码然后执行python3 new_server.py的话，实际上只是运行了一下这段代码，作用是把网页的内容打印出来了。没有启动服务器。启动服务器的代码是上次我们一起改的那个test.py。里面的“Flask”模块是用来搭建python服务器的，你可以简单了解一下python Flask。
4. 你可以把我上面的代码集成到test.py里面，让def home():这个函数不是简单的返回hello这个字符串，而是网页的内容

**Comment by jeremyjia** [comment]
具体的步骤：
1. 集成我的上面的代码到test.py中
2. 运行python3 test.py，启动服务器
3. 浏览器输入http://localhost:5000, 应该能看到URL指定的那个体育的网页，你可以随意替换这个URL

**Comment by waynexw** [comment]
备注：
进行到第二步python3 test.py，启动服务器，报错ModuleNotFoundError: No module named 'flask'
随即进行安装  pip install flask
再启动服务器python test.py 成功，python3 test.py启动不成功。

合并代码如下：
from flask import Flask
import urllib.request
app = Flask("__main__")

@app.route("/")    
def home():
    url = 'http://news.baidu.com/internet'
    #创建request对象
    req = urllib.request.Request(url)
    #发送请求，获取结果
    with urllib.request.urlopen(req) as response:
        data = response.read()
        content = data.decode()
    #print(content)
    return content
if __name__ == "__main__":
    app.run()

运行python test_serverofnews, 本地服务器localhost: 5000 打印目标网页成功。
