### ISSUE TITLE
实现canvas context.fillStyle

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#346]
- [ ] 在解析引擎中实现context.fillStyle = "hsla(0,100%,50%,1)";  （暂缓实现）
- [x] 在解析引擎中实现context.fillStyle = "#0000ff";
- [x] 以下测试用例中，烟花颜色效果应该一致         （由于没有实现上述hsla函数，无法做到色彩完全一致）
        http://localhost:8080/blfw.html
        http://localhost:8080/image/video?script=firework.json

**Comment by littleflute** [comment]
- [ ] 注意第2行红色的字，时间格式也不一致（code 应该是 var d = new Date(); 
    ctx.fillText( d.toLocaleString(), 110, 88);

**Comment by jeremyjia** [comment]
实现hsla这个函数还有点复杂，此次升级只是实现了
 ctx.fillStyle = "#0000ff";
 ctx.strokeStyle = "#FF00AF";
这种颜色表达

**Comment by jeremyjia** [comment]
这是目前的测试效果：
https://user-images.githubusercontent.com/17973348/118947573-0eceee80-b98a-11eb-98c8-05643f578fa5.mp4
