### ISSUE TITLE
乱码bug refer to #353

### ISSUE THREAD

**Issue by waynexw** [jeremyjia/Games#356]
@jeremyjia 运行#353实例时，在我的计算机环境下，发现生成的视频中有乱码。
![image](https://user-images.githubusercontent.com/72367965/119078373-6a0bea00-ba39-11eb-94db-e3cb4396801e.png)

**Comment by jeremyjia** [comment]
java -Dfile.encoding=utf-8 -jar pbz-demo-1.0.5-SNAPSHOT.jar

**Comment by waynexw** [comment]
我用java -Dfile.encoding=utf-8 -jar pbz-demo-1.0.5-SNAPSHOT.jar命令运行服务器，可以正常启动。
但是我忘记如何复现乱码问题了，当时是黄老师带着我操作。
我点击video gerneration后，界面是这样的：
![image](https://user-images.githubusercontent.com/72367965/119443070-4a8ffc80-bd6c-11eb-8785-2597a51cdf19.png)
另外我注意到软件版本号也不同，我现在看到的是plx/p1.js_v0.242，而那天出现乱码问题的版本号是myplx1.js_v0.36，所以我觉得我没有进入到正确的功能模块。
@jeremyjia 如何能进入到有乱码的这个界面，请有空儿时指教。

**Comment by jeremyjia** [comment]
@waynexw 关于乱码问题，我们只要找一个含有中文的剧本就可以了测试了，可以试试以下两个测试用例，启动服务程序后，在浏览器地址栏里面输入下面的地址：

http://localhost:8080/image/video?script=video1.json
http://localhost:8080/image/video?script=video12.json

如果启动服务程序的时候不加-Dfile.encoding=utf-8这个参数，应该能够重现乱码问题，加了以后可以显示正常的中文了

**Comment by waynexw** [comment]
![image](https://user-images.githubusercontent.com/72367965/119594014-5e943680-be1e-11eb-8d10-b367a6d6a033.png)
启动服务程序的时候加-Dfile.encoding=utf-8这个参数，在我的环境下证明不再出现乱码了。多谢 @jeremyjia
