### ISSUE TITLE
cchess user case: https://littleflute.github.io/cchess/index1.html

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#362]
在 xd 分支下，对比测试：
https://littleflute.github.io/cchess/index1.html
http://localhost:8080/image/json2video?script=video12.json

https://raw.githubusercontent.com/littleflute/cchess/master/blCChess.json
http://localhost:8080/image/json2video?script=https://raw.githubusercontent.com/littleflute/cchess/master/blCChess.json&&video=blCChess.mp4

https://raw.githubusercontent.com/littleflute/cchess/master/blCChess1.json
http://localhost:8080/image/json2video?script=https://raw.githubusercontent.com/littleflute/cchess/master/blCChess1.json&&video=blCChess1.mp4

**Comment by jeremyjia** [comment]
我的机器上测试结果背景颜色是红色的，估计是 _ctx.fillStyle = "lightblue"; 不支持这个颜色的写法

**Comment by jeremyjia** [comment]
fixed above in #365

**Comment by littleflute** [comment]
http://localhost:8080/image/json2video?script=video12.json&&video=chess1.mp4
