### ISSUE TITLE
endpoint: json2video

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#364]
说明：之前的 endpoint 'http://localhost:8080/image/video?script=example.json' , 生成的视频文件名是固定的，现需要生成可设置文件名的。(可分派给其他成员做）

调用形式如下所示：
http://localhost:8080/image/json2video?script=video.json&video=v1.mp4

- [x] script值为任意有效剧本，可以为任意可访问的网址
- [x] video 为生成的文件，由调用者设定文件名。 为ffmpeg 支持的视频文件，如 *.mp4, *.mkv,...
- [x] 在此生成 基本的测试链接。
- [x] 升级swaggerUI
- [x] http://localhost:8080/image/json2video?script=https://littleflute.github.io/vle202110/t.json&video=t.mp4
         script:  https://littleflute.github.io/vle202110/t.json
         mp3: https://github.com/littleflute/vle202111/raw/blog/05/ac20211105a1.mp3

**Comment by jeremyjia** [comment]
Please verify it based on python branch.
