### ISSUE TITLE
How to use Python to translate any Youtube video's subtitle to your language

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#370]
https://www.youtube.com/watch?v=nc5EhK12QUw

**Comment by waynexw** [comment]
Have completed this example according to the video, and the test's result as below:
0.64
哟，怎么了欢迎回到我的 
2.0
YouTube频道今天我会告诉你们 
3.6
你怎么能笑 
4.72
拿任何YouTube视频字幕和 
7.2
翻译成你所知道的更喜欢 
9.04
语 
9.679
所以让我们说你继续你的你 
11.84
了解YouTube. 
12.719
并搜索kizuna，即uh喜欢 
16.32
介绍 
19.199
而你所以你点击它，然后点击你 
21.119
单击字幕 
23.92
哦，这是英语在这里有时如此 
26.16
只有日本人或者
