### ISSUE TITLE
恢复issue 118 的接口并做验收测试

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#375]
- [x] 恢复 #118 的接口实现的功能 （jeremy）
@waynexw 这是我们以前开发的一个小功能，我之前加了一些用户登陆的限制，现在我把这个限制去掉了，你来做一下验收测试，请先把pull request approve and merger：https://github.com/jeremyjia/Games/pull/377
这样你可以在master分支上进行下面的测试，否则你需要到python分之上进行测试

基本功能测试用例
- [x] 启动服务程序 java -jar pbz-demo-1.0.8-SNAPSHOT.jar
- [x] 在浏览器里输入http://localhost:8080/image/clock?time=3:5:40  (1.0.7 运行是这样的：{"code":500,"message":"Please login first!","reason-phrase":"Internal Server Error","exception-class":"java.lang.Exception"}）
- [x] 在浏览器里会看到闹钟的图片
- [x] 请wangxy完成下面的验收测试

**Comment by jeremyjia** [comment]
@waynexw 这是我们以前开发的一个小功能，我之前加了一些用户登陆的限制，现在我把这个限制去掉了，你来做一下验收测试

- [ ] 测试用例1
1. 启动服务程序 java -jar pbz-demo-0.0.8-SNAPSHOT.jar
2. 在浏览器里输入http://localhost:8080/image/clock?time=3:5:40
3. 在浏览器里会看到闹钟的图片

- [ ] 测试用例2
1. 启动服务程序 java -jar pbz-demo-0.0.8-SNAPSHOT.jar
2. 在命令行里输入curl http://localhost:8080/image/clock?time=10:20:15 -o 1.jpg（需要安装一下curl命令）
3. 会在当前目录下生成一幅闹钟图片"1.jpg"

- [ ] 测试用例3 
1. 启动服务程序 java -jar pbz-demo-0.0.8-SNAPSHOT.jar。
2. CD到 Games\issues\119 目录下
3. 运行 r60.bat生成 60张图。
3. 运行 jpg2v.bat 生成 vs60s.mp4。运行格式 jpg2v 360。
4. 运行 mp4i.bat 生成 index.html。
5. 运行 index.html, 在 网页上点 [v60s.mp4]铵钮，应看到播放效果。

**Comment by waynexw** [comment]
![1](https://user-images.githubusercontent.com/72367965/120265899-3f951900-c2e4-11eb-8bab-ad9ff6440cbc.jpg)
多谢 @jeremyjia 
步骤介绍清晰，顺利完成测试。
