### ISSUE TITLE
https://www.geeksforgeeks.org/create-transparent-png-image-with-python-pillow/

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#386]
https://www.geeksforgeeks.org/create-transparent-png-image-with-python-pillow/

**Comment by waynexw** [comment]
![transparent_image](https://user-images.githubusercontent.com/72367965/120409939-5d6e8680-c395-11eb-8224-ad65526e6b38.png)
Using a picture to verify the article, and the test shows all black colour has been deleted.
