### ISSUE TITLE
python+swagger 主程序重构

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#412]
- [x] 把 python 目录下的 i7321 目录 重命名为 swagger
- [x] http://localhost:5000/ ,让此url 可访问到有意义的内容（1. 显示当前日期和时间 2. 内含一个链接可跳到 http://localhost:5000/swagger/ ）
- [x] http://localhost:5000/swagger/ 让url 显示的版本号为 1.0.1 (原来是 1.0.0)

**Comment by littleflute** [comment]
ref: https://realpython.com/flask-blueprint/

**Comment by waynexw** [comment]
![image](https://user-images.githubusercontent.com/72367965/121762123-5571cc00-cb77-11eb-9396-d31a0a2686ce.png)
