### ISSUE TITLE
验证现有的command API可以调用python代码

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#413]
目的：验证现有的基于Java实现的command endpoint API可以成功调用python程序(xxx.py)

步骤：

- [x] 启动服务程序java -jar pbz-demo-1.0.9-SNAPSHOT.jar
- [x] 在浏览器输入http://localhost:8080/uploadpage
- [x] 在上步的文件选择页面，选择一个本地的(xxx.py)文件上传到服务器。这里我选择一个test.py, 该文件中只有一句简单的代码print("Hello this is jeremy!")
- [x] 在浏览器输入http://localhost:8080/command?cmd=python3%20test.py
- [x] 如果成功，应该看到{"Status":"OK!","Message":"STDOUT: Hello this is jeremy!\n"}

注意我的Mac是python3命令，可以根据自己的环境输入python, py等，后面的%20表示空格一定要有

**Comment by jeremyjia** [comment]
@waynexw 我已经验证成功了最简单的情况，你可以先试试，然后参考我上面的步骤，验证一下稍微复杂的python代码和参数是否可行，如果python程序本身有输出，比如out.txt，可以在完成上面的步骤后，输入localhost:8080/out.txt查看到它

可以把你测试的python上传到Games/python/i413目录下

**Comment by waynexw** [comment]
运行命令 http://localhost:8080/command?cmd=py%20download_youtube_srt.py
查看到文件输出 http://localhost:8080/srt_file.txt
测试通过  测试的python文件已上传到wx分支的Games/python/i413目录下。
