### ISSUE TITLE
实现书籍数据保存到文件和数据库等功能。swagger

### ISSUE THREAD

**Issue by waynexw** [jeremyjia/Games#427]
实现书籍数据保存到文件和数据库等功能。

**Comment by jeremyjia** [comment]
@waynexw 我写了一个读取数据的例子供你参考：
Games\python\sample\test_readfile.py

**Comment by waynexw** [comment]
> @waynexw 我写了一个读取数据的例子供你参考：
> Games\python\sample\test_readfile.py

@jeremyjia 多谢，我稍后学习学习。

**Comment by waynexw** [comment]
useful reference: https://www.cnblogs.com/bigberg/p/6430095.html
json dumps把数据类型转换成字符串 dump把数据类型转换成字符串并存储在文件中;
loads把字符串转换成数据类型  load把文件打开从字符串转换成数据类型。
