### ISSUE TITLE
为剧本增加音频对象

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#445]
- [x]  new Object type: audio
- [x]  unit test    
         http://localhost:8080/image/json2video?script=video14.json

ref: https://github.com/jeremyjia/Games/pull/444

**Comment by jeremyjia** [comment]
https://user-images.githubusercontent.com/17973348/127731902-2270f7a6-c324-45f3-9d52-b02ae6a12b35.mp4

**Comment by jeremyjia** [comment]
剧本协议：

"audioObjects": [
			{
                "start": "0",
                "audioFile": "A_Sax.wav",
			},       
            {
                "start": "1",
                "audioFile": "A_Bass.wav",
            },
			{
                "start": "2",
                "audioFile": "A_Sax.wav",
            },
			{
                "start": "3",
                "audioFile": "A_Bass.wav",
            },
			{
                "start": "4",
                "audioFile": "A_Sax.wav",
            },
			{
                "start": "5",
                "audioFile": "A_Bass.wav",
            },
			{
                "start": "6",
                "audioFile": "A_Sax.wav",
            },
			{
                "start": "7",
                "audioFile": "A_Bass.wav",
            },
			{
                "start": "8",
                "audioFile": "A_Sax.wav",
            },
			{
                "start": "9",
                "audioFile": "A_Bass.wav",
            },
			{
                "start": "10",
                "audioFile": "A_Sax.wav",
            },
			{
                "start": "11",
                "audioFile": "A_Bass.wav",
            },
			{
                "start": "13",
                "audioFile": "A_Sax.wav",
            },
			{
                "start": "15",
                "audioFile": "A_Bass.wav",
            },
			{
                "start": "17",
                "audioFile": "A_Sax.wav",
            },
			{
                "start": "19",
                "audioFile": "A_Bass.wav",
            }
        ],
