### ISSUE TITLE
voa2Video feature failed by error message "Malformed reply from SOCKS server"

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#449]
This looks like a bug created this for tracking.

{"code":500,"message":"Malformed reply from SOCKS server","reason-phrase":"Internal Server Error","exception-class":"java.net.SocketException"}

**Comment by jeremyjia** [comment]
<img width="491" alt="截屏2021-06-27 下午1 03 52" src="https://user-images.githubusercontent.com/17973348/123533570-1a5fc300-d749-11eb-8679-254c0e312816.png">

**Comment by littleflute** [comment]
![image](https://user-images.githubusercontent.com/17950965/124031089-bb4db880-d9ab-11eb-8b11-978d9260c90d.png)

**Comment by jeremyjia** [comment]
已经找到这个问题的原因和解决办法：
将下面这句加到  "/etc/hosts"里面，Windows上是"C:\Windows\System32\drivers\etc\hosts"

23.193.155.91 learningenglish.voanews.com

**Comment by jeremyjia** [comment]
配置以上域名解析后，URL可以成功访问
http://localhost:8080/download?url=https://learningenglish.voanews.com/z/3521&filename=AsItIs.html

{"pathOnServer":"/Users/jeremy/Downloads/jiadev/Games/Spring/target/AsItIs.html","code":200,"filename":"AsItIs.html","message":"文件下载成功, 花费时间:1153ms"}

**Comment by littleflute** [comment]
64 bytes from a23-6-167-31.deploy.static.akamaitechnologies.com (23.6.167.31): icmp_seq=1 ttl=35 time=6.25 ms
