### ISSUE TITLE
chat Log

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#45]
Let's chat
xd:谁有空可在这里聊天，讨论本聊天室的需求

xd1:tttt
xd1:xxxxx
jeremyjia:根据官方文档，我猜测，使用不同Github用户创建的token可以解决HTTP 403的错误
jeremyjia:https://developer.github.com/v3/ 
jeremyjia:这个Get online User，目前的数据是假的，我会继续设计后台数据库的存储格式。。。。我本来想把这个Div放到主窗口的右边，但是我不会改它的Style设置，所以暂时先这样了
Please use "cmd:number" format to load our plugins.
xd:Hi
xd:Hello
Esp:Hi
Esp:Great!
Esp:Hello!
aaa:asdfkals;df
Esp:No previous messages
2019-09-26 09:41:25
EZ1G5H:sent from phone
jeremy:just test it

**Comment by jeremyjia** [comment]
Let's chat
2022-02-21 17:59:03
jiapeng:https://register.advent.com/selfEnrollment/index.aspx?code=jT9NGprVaeIJNQ69WzHMI6wUd 
2022-03-12 23:12:16
g:https://hub.fastgit.org/jeremyjia/Games/issues
2022-03-15 16:26:11
11:https://urldefense.com/v3/__https://dwz.cn/qbQZOtgG__;!!JE2nyJ8!l59McoIiT4EFNxgoYdOQ61upqxj7ntt-Eni9l0SiQzVu9MmQtHZXCyDxQ5uM0TH_$
2022-03-19 14:20:13
da:https://blog.csdn.net/weixin_42231795/article/details/105514994?spm=1001.2101.3001.6650.12&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-12.pc_relevant_paycolumn_v3&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-12.pc_relevant_paycolumn_v3&utm_relevant_index=18
2022-04-11 21:53:40
a:ok
2022-05-28 07:22:49
b:Content-Type--->[application/json; charset=utf-8]X-Content-Type-Options--->[nosniff]X-RateLimit-Reset--->[1653694684]Date--->[Fri, 27 May 2022 23:20:22 GMT]Cache-Control--->[private, max-age=60, s-maxage=60]ETag--->["bc2f8a14645a826b88b25526583372854693398192cf25d552eb58cf759826fc"]Vary--->[Accept-Encoding, Accept, X-Requested-With, Accept, Authorization, Cookie, X-GitHub-OTP]X-RateLimit-Limit--->[5000]X-OAuth-Scopes--->[admin:enterprise, admin:gpg_key, admin:org, admin:org_hook, admin:public_key, admin:repo_hook, delete:packages, delete_repo, gist, notifications, repo, user, workflow, write:discussion, write:packages]0
2022-05-28 14:56:34
b:a
Please use "cmd:number" format to load our plugins.
Please use "cmd:number" format to load our plugins.
