### ISSUE TITLE
GitHub主页实现定制功能

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#50]
主页上的主框架风格是统一的，但Body部分可以根据不同的User展示不同的内容
如目前源主页上显示唐老鸭和天气预报，其他人可以显示不同的内容，而这种定制和修改应该是简单方便的

**Comment by littleflute** [comment]
https://github.com/jeremyjia/Games/issues/95

**Comment by littleflute** [comment]
#96
