### ISSUE TITLE
Python数据的图表显示

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#542]
@waynex 我想到的一个需求，不着急做，有空研究，可以放到下一个sprint

需求：根据一组输入的数据，做出统计图并保存成图片，如柱状图，饼状图，折线图

- [x] 调研如何用python来实现此功能
- [x]  可以拟定一个具体的业务场景，细化并实现

**Comment by waynexw** [comment]
- [ ] 业务场景1：从excel表中输入数据
