### ISSUE TITLE
在i528中仿写测试用例

### ISSUE THREAD

**Issue by waynexw** [jeremyjia/Games#562]
调用python生成柱状图并生成视频，在i528中测试。

**Comment by waynexw** [comment]
@jeremyjia 请教问题，多谢前天你帮我merge的那个新剧本 example 3。但此剧本运行后报错。我估计是我写的参数出问题了。我现在想排查一下哪儿写错了。
我试图从spring的目录下 找出哪个是对应编译我这个剧本的文件，看看里面是怎么写的，以及确定我传递的参数是不是冲突。不过spring里的文件夹和文件太多了，远多于我之前做的那个swagger，看得有点茫然。
![image](https://user-images.githubusercontent.com/72367965/141026316-588fb3bf-dbda-488e-a2c3-65bef3bd22fe.png)
![image](https://user-images.githubusercontent.com/72367965/141027421-db5a6fc5-fa08-4787-8215-7f2aa67ede18.png)

**Comment by waynexw** [comment]
> @waynexw 在我的macOS环境可以成功运行Sample3， 得到柱状图的视频，效果不错！可以参考以下办法查找问题：
> 
> * [ ]  在服务程序所在目录下面查看这个文件Cmdlog.txt，查看报错的时候里面写了什么
> * [ ]  单独运行你的python插件bar_chart_excel.py，用python运行，例如，python bar_chart_excel.py -i 1.xlsx
>   一般情况下，单独运行命令可以成功，但集成后不成功的话，有可能是我这边的问题
> * [ ]  有时间的时候可以在虚拟机上测试一下

多谢 我再测测。

**Comment by jeremyjia** [comment]
@waynexw 从Cmdlog.txt的内容，我已经知道问题的原因了，建议如下：

- [ ] 重新编译服务程序mvn clean install -DskipTests， 然后测试

备注：重新编译服务程序会清理服务程序下的全部文件，确保使用的是最新的插件

**Comment by waynexw** [comment]
> @waynexw 从Cmdlog.txt的内容，我已经知道问题的原因了，建议如下：
> 
> * [x]  重新编译服务程序mvn clean install -DskipTests， 然后测试
> 
> 备注：重新编译服务程序会清理服务程序下的全部文件，确保使用的是最新的插件

多谢多谢。这回测试通过了。看了你的备注，终于明白为什么之前测试通不过了。学习了！
