### ISSUE TITLE
upgrade for btn-6

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#563]
主页的6号

- [x] 图片，视频，音频中的浏览按钮实现选中高亮 (Only picture is Done)
- [x] 选中后增加删除功能 （Only picture is done）

**Comment by littleflute** [comment]
- [ ] https://littleflute.github.io/Games/issues/563/

**Comment by littleflute** [comment]
ref: https://docs.github.com/en/rest/reference/issues#comments
