### ISSUE TITLE
Python绘制正态分布，把加眼镜的python程序的参数提取出来

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#566]
@waynexw 这个任务分给你，有空的时候研究一下

- [x] 学习案例： https://blog.csdn.net/qq_41503174/article/details/99206324
- [x] 模仿之前的水波纹插件、柱状图插件，制作一个正态分布图插件，合理提取参数
- [x] 制作出一个剧本，并能生成相应的视频(制作好的剧本还可以放到i528中)

- [x] 把为照片加眼镜的python程序的参数提取出来

**Comment by waynexw** [comment]
-i 必须是文件名 图片或文档
-o 必须是输出的图片名
以上两个是不能缺少和更改文件类型的。

**Comment by waynexw** [comment]
研究并实例化 https://github.com/hhuayuan/jianying-srt/blob/master/jianying-srt.py

**Comment by jeremyjia** [comment]
戴眼镜的算法有些问题，根本原因是人脸识别算法本身有些瑕疵
1. 眼睛的识别，有时候会把鼻孔误以为眼睛

记录此问题
