### ISSUE TITLE
升级endpoint http://localhost:8080/image/combine，支持LRC格式的字幕文件

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#568]
- [x] 升级服务程序，支持LRC格式的字幕文件
- [x] 音频和字幕文件可以取自网站: https://www.51voa.com/VOA_Special_English/what-is-space-junk-and-how-dangerous-is-it-88001.html
- [x] 构建如下的测试用例：
    1. 启动服务程序1.0.25
    2. 浏览器运行：http://localhost:8080/image/combine?subtitlefile=https://www.51voa.com/lrc/202111/what-is-space-junk-and-how-dangerous-is-it.lrc&audiofile=https://files.51voa.cn/202111/what-is-space-junk-and-how-dangerous-is-it.mp3&bgfile=https://img.51voa.cn/1/4D7802F8-1010-49BA-8CB6-FD127087CE09_cx0_cy10_cw0_w268_r1.jpg

**Comment by jeremyjia** [comment]
http://localhost:8080/image/combine?subtitlefile=https://www.51voa.com/lrc/202111/what-is-space-junk-and-how-dangerous-is-it.lrc&audiofile=https://files.51voa.cn/202111/what-is-space-junk-and-how-dangerous-is-it.mp3&bgfile=https://img.51voa.cn/1/4D7802F8-1010-49BA-8CB6-FD127087CE09_cx0_cy10_cw0_w268_r1.jpg

**Comment by jeremyjia** [comment]
https://user-images.githubusercontent.com/17973348/142770142-6a891eb3-4972-4a67-bac4-cdc23ad840bf.mp4


Uploading vFinal.mp4…

**Comment by littleflute** [comment]
http://localhost:8080/image/combine?subtitlefile=https://files.51voa.cn/202111/nasa-prepares-to-launch-asteroid-defense-test-mission.mp3&audiofile=https://www.51voa.com/lrc/202111/nasa-prepares-to-launch-asteroid-defense-test-mission.lrc&bgfile=https://img.51voa.cn/1/C501D07B-81C5-462A-89C8-E630C2DD9A1F_w268_r1.jpg

**Comment by littleflute** [comment]
http://localhost:8080/image/combine?audiofile=https://files.51voa.cn/202111/researchers-large-language-family-had-ancient-origins-in-china.mp3&subtitlefile=https://www.51voa.com/lrc/202111/researchers-large-language-family-had-ancient-origins-in-china.lrc&bgfile=https://img.51voa.cn/1/B5382DC9-19B1-4093-ADA9-525BCBEF2548_cx0_cy10_cw0_w268_r1.jpg

**Comment by littleflute** [comment]
http://localhost:8080/image/combine?audiofile=https://files.51voa.cn/202111/monarch-butterflies-return-to-california.mp3&subtitlefile=https://www.51voa.com/lrc/202111/monarch-butterflies-return-to-california.lrc&bgfile=https://img.51voa.cn/1/EEFD94F7-5912-441A-8580-CFE9D55639E8_cx0_cy10_cw0_w268_r1.jpg

**Comment by littleflute** [comment]
http://localhost:8080/image/combine?audiofile=https://data.51voa.cn/201002/se-pia-jackson-pollock-21feb10_0.mp3&subtitlefile=https://www.51voa.com/lrc/202111/let-s-talk-about-our-shadow.lrc@bgfile=https://img.51voa.cn/1/8097400c-77f4-4008-bd4b-0e4cc5f74fef_w268_r1.jpg

**Comment by littleflute** [comment]
http://localhost:8080/image/combine?audiofile=https://files.51voa.cn/202111/congress-mandates-new-car-technology-to-stop-drunken-driving.mp3&subtitlefile=https://www.51voa.com/lrc/202111/congress-mandates-new-car-technology-to-stop-drunken-driving.lrc&bgfile=https://img.51voa.cn/1/D91861B7-6139-4BE7-950F-E9599C25AD4A_w268_r0.jpg

**Comment by littleflute** [comment]
http://localhost:8080/image/combine?audiofile=https://github.com/littleflute/vle202111/22/vle.mp3&subtitlefile=https://www.51voa.com/lrc/202111/let-s-talk-about-our-shadow.lrc&bgfile=https://github.com/littleflute/vle202111/21/as11.jpg
