### ISSUE TITLE
agenda: 02/13/2022

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#627]
- [ ] #625 

- [ ] #632

**Comment by jeremyjia** [comment]
常用软件下载：

1. WPS www.wps.cn

**Comment by jeremyjia** [comment]
QT:

 https://download.qt.io/development_releases/prebuilt/mingw_32/
 
 加速下载网站：
 https://mirrors.tuna.tsinghua.edu.cn/qt/
 
 
 QT:
   学习
   https://github.com/devbian/qt_simu360
   

eclipse download address:
  http://mirrors.ustc.edu.cn/eclipse/technology/epp/downloads/release/

refresh page
https://blog.csdn.net/xiaoya_syt/article/details/77879194
