### ISSUE TITLE
hack: http://jiqie.zhenbi.com/a/m14.htm

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#630]
http://jiqie.zhenbi.com/a/m14.htm

**Comment by littleflute** [comment]
https://stackoverflow.com/questions/47060534/how-do-post-request-in-puppeteer

**Comment by littleflute** [comment]
curl -X POST "http://localhost:8080/api/checkUserName?UserName=aaa2"

**Comment by littleflute** [comment]
curl -X POST "https://jiqie.zhenbi.com/a/re13.php"

**Comment by littleflute** [comment]
curl -X POST "https://jiqie.zhenbi.com/a/re14.php?id=%E5%88%98%E5%BE%B7%E5%8D%8E&zhenbi=20191123&id1=905&id2=14&id3=%230000FF&id5=%23FFFFFF" -H "content-length: 149 "

**Comment by jeremyjia** [comment]
@littleflute 
我请xiyu帮忙调研了一下，她实现了这个功能

**Comment by jeremyjia** [comment]
System.setProperty("webdriver.chrome.driver", "../bin/chromedriver.exe");
