### ISSUE TITLE
${VAR_TIME} 预定义关键字

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#644]
- [x] relationship : ${VAR_TIME} , rate, times

**Comment by jeremyjia** [comment]
@littleflute 黄老师是不是发现什么问题了？

**Comment by littleflute** [comment]
> @littleflute 黄老师是不是发现什么问题了？

${VAR_TIME} 剧本中这个宏变量不需定义就能用，相当于剧本有关键字了。

**Comment by jeremyjia** [comment]
@littleflute 
是的，目前我定义了两个这样的关键字：

${VAR_TIME}  ：表示视频的时长，单位秒
${VAR_FRAMES} ： 表示视频总共多少张图片，这个宏已经把帧率考虑进去了，相当于 rate*time
