### ISSUE TITLE
JDSpider

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#66]
获取京东商城的商品信息的爬虫

**Comment by jeremyjia** [comment]
根据对jsoup的学习和网上的一些代码，基于Libgdx开发了一个爬起京东商城商品的App
1. 输入商品，如kouzhao，点击Search，可以列出爬取到的商品信息，商家地址，和是否有货的信息
2.程序缺陷：
       2.1  Libgdx对中文的支持较差，只能支持少量的中文显示，
       2.2  商家Link不能点击跳转，这个不知道Libgdx是否有支持的控件
       2.3 只列出了6，7条数据，应该使用一个类似ListView的控件去显示

**Comment by jeremyjia** [comment]
<img width="557" alt="Screen Shot 2020-02-04 at 3 06 03 PM" src="https://user-images.githubusercontent.com/17973348/73722548-b73f4c00-4761-11ea-94d9-57cb87820fe8.png">

**Comment by littleflute** [comment]
![image](https://user-images.githubusercontent.com/17950965/73727633-bae1bd00-46e6-11ea-8f71-8019a9b82956.png)
我试编译了一下，没通过。我不知道什么原因，如上图提示。

**Comment by littleflute** [comment]
prjCrawler 是个不错的项目。
但再开发流程上应该按正规的方式开发（建立专门的branch,功能实现后，再merge到master branch）。
master branch 的一个基本特性是：随时都可以编译通过并可运行的。
