### ISSUE TITLE
将JDSpider按照竖屏在Android上显示

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#67]
建立分支jiadev用于完成此项任务

**Comment by jeremyjia** [comment]
代码已经上传到jiadev，等待merge到master

**Comment by jeremyjia** [comment]
<img width="611" alt="Screen Shot 2020-02-07 at 11 45 50 AM" src="https://user-images.githubusercontent.com/17973348/73999373-88aeb480-499f-11ea-81dd-9d32bc84cf29.png">

**Comment by littleflute** [comment]
I just checked out the branch "jiadev" and compiled and ran the App. Every thing goes well. Good job!

**Comment by jeremyjia** [comment]
Thanks, done merge to master.
