### ISSUE TITLE
Javascript绘图引擎

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#73]
利用Java的ScriptEngineManager，实现一个能够解析Javascript绘图脚本的引擎。
ScriptEngineManager可以执行基本的JS，但无法获取只有浏览器才支持的document对象，也不能解析HTML5的 Canvas Context绘图对象，因此我们只能自己写代码扩展来实现。

基本需求如下，给定一段Javascript脚本，该脚本实现的功能是绘制图形，如圆，矩形等。
写一个Java Android App可以解析这段Javascript脚本并绘制出相应的图形

**Comment by jeremyjia** [comment]
需要如下，给定一段Javascript脚本，脚本实现的功能是绘制图形，如圆，矩形等。
写一个App程序可以解析这段Javascript脚本并绘制出相应的图形

**Comment by jeremyjia** [comment]
alert('abc'); var canvas=document.getElementById('canvas'); var context=canvas.getContext('2d'); for(var i=0;i<3;i++){context.beginPath(i);}

**Comment by jeremyjia** [comment]
alert("Javascript Engine Test...");
var canvas=document.getElementById('canvas1');
var context=canvas.getContext('2d');
context.fillStyle = "Red";
var img = new Image();
img.src="https://raw.githubusercontent.com/jeremyjia/Games/master/issues/4/images/bb.gif";
context.drawImage(img,100,100);

**Comment by jeremyjia** [comment]
var x=1;
setInterval(function(){
x++;
alert(x);
},1000);

**Comment by littleflute** [comment]
var canvas=document.getElementById('canvas1');
var ctx=canvas.getContext('2d');
var img = new Image();
img.src="images/board.jpg";
ctx.drawImage(img,0,0);

bl$("canvas1").onclick = function(event)
{
var x = event.offsetX;
var y = event.offsetY;
alert(x+","+y);
img.src="https://raw.githubusercontent.com/jeremyjia/Games/master/issues/4/images/bb.gif";
ctx.drawImage(img,x,y);
}

**Comment by littleflute** [comment]
alert("xd1:" + this.parentElement.id);
