### ISSUE TITLE
color

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#736]
杏仁黄    rgb(250, 249, 222)   秋叶褐    rgb(255, 242, 226)
胭脂红    rgb(253, 230, 224)   青草绿    rgb(227, 237, 205)   海天蓝    rgb(220, 226, 241)
葛巾紫    rgb(233, 235, 254)   极光灰    rgb(234, 234, 239)

**Comment by littleflute** [comment]
#FAF9DE (250,249,222) //杏仁黄

**Comment by littleflute** [comment]
#FFF2E2 (255,242,226) //秋叶褐
