### ISSUE TITLE
agenda: 07/2/2022 & 07/16/2022

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#780]
Jeremyjia:

- [x] #773  docker image，演示将Springboot工程制作成一个Docker image
       1. mvn clean install -DskipTests
       2. docker build -t springbootimg1 .
       3. docker run -p 8080:8080 -t -i springbootimg1
- [x] TLV：xiyu最近在研究这种数据通信格式，处供参考，https://www.likecs.com/show-204679027.html
- [x] TBD：集成到maven工程，http://archive.apache.org/dist/ （mvn package docker:build -DskipTests）
- [x] cloud native doc: https://dotnet.microsoft.com/en-us/download/e-book/cloud-native-azure/pdf

**Comment by jeremyjia** [comment]
https://www.runoob.com/docker/docker-architecture.html

**Comment by jeremyjia** [comment]
https://blog.csdn.net/lu1171901273/article/details/123575982

**Comment by jeremyjia** [comment]
#查看镜像列表
docker images
#删除单个镜像
docker rmi image-id
#删除所有镜像
docker rmi $(docker images -q)
#查看运行中的容器
docker ps
#查看所有容器
docker ps -a
#停止单个容器
docker stop container-id
#停止所有容器
docker stop $(docker ps -a -q)
#删除单个容器
docker rm container-id
#删除所有容器
docker rm $(docker ps -a -q)

**Comment by jeremyjia** [comment]
https://wenku.baidu.com/view/4d311afea68da0116c175f0e7cd184254b351b13.html

**Comment by littleflute** [comment]
https://meet.google.com/phw-saij-szz?authuser=0
