### ISSUE TITLE
8/27 & 07/30 & 07/23 2022

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#792]
jeremyjia：

- [x] dynamic add useful link #793
       https://waynexw.github.io/Games/
- [x] 商品列表网站 https://jeremyjia.github.io/Games/issues/53/i.html#
这个是黄老师收集的一个例子，只有不完整的前端页面，我的想法是, 我们把它完整的实现了

**Comment by jeremyjia** [comment]
https://jeremyjia.github.io/Games/issues/53/i.html#

**Comment by jeremyjia** [comment]
https://github.com/haoguanjun/cloud_native_sample

**Comment by jeremyjia** [comment]
https://docs.microsoft.com/en-us/learn/modules/dotnet-microservices/2-what-are-microservices

**Comment by jeremyjia** [comment]
C++11/17
https://changkun.de/modern-cpp/zh-cn/00-preface/

**Comment by jeremyjia** [comment]
function func(){
 var temp = 1;
return function(){ alert(++temp);}
}
var getv = func();
getv();
getv();

**Comment by jeremyjia** [comment]
https://code.ssnc.dev/jjia1

**Comment by waynexw** [comment]
<!DOCTYPE html>
<html>
<body>

<h1>The Document Object</h1>
<h2>The getElementById() Method</h2>

<p id="demo"></p>

<a style="border: red solid 3px; color: red" id="a1" href="http://baidu.com"> abc </a>

<p>
<button onclick=f()> change color </button>
</p>

<script>
document.getElementById("demo").innerHTML = "Hello World";

function f(){ a1.style.color="green";
}
</script>

</body>
</html>

**Comment by jeremyjia** [comment]
What Is Short Covering?
Short covering refers to buying back borrowed securities in order to close out an open short position at a profit or loss. It requires purchasing the same security that was initially [sold short](https://www.investopedia.com/terms/s/shortselling.asp), and handing back the shares initially borrowed for the short sale. This type of transaction is referred to as [buy to cover](https://www.investopedia.com/terms/b/buytocover.asp).

For example, a trader sells short 100 shares of XYZ at $20, based on the opinion those shares will head lower. When XYZ declines to $15, the trader buys back XYZ to cover the short position, booking a $500 profit from the sale.
