### ISSUE TITLE
add useful link

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#793]
//以下代码用于动态添加有用的网站链接
var v = bl$("id_div_4_useful_link");
v.innerHTML += ":-)";
v.dv = blo0.blDiv(v,v.id+"dv","Useful Website:",blGrey[0]);

//读取数据回调
function _CBComments(o) {
var _i = 0;
var _v = v.dv;
for(i in o){
_i++;
var body = o[i].body;
var obj = JSON.parse(body);
var name="<br>"+_i+"."+obj.name; //在各网站之间填加空格, 或者换行等等
var link = obj.link;
var oA = blo0.blLink(_v, _v.id+"link"+_i,name,link,blGrey[0]);
}
}
var _src = "https://api.github.com/repos/jeremyjia/Games/issues/793/comments";
w3.getHttpObject(_src, _CBComments);

**Comment by jeremyjia** [comment]
test

**Comment by jeremyjia** [comment]
www.baidu.com

**Comment by jeremyjia** [comment]
{"name":"ddddddd","link":"https://www.runoob.com"}

**Comment by jeremyjia** [comment]
{"name":"好吃的","link":"https://www.w3schools.com"}

**Comment by waynexw** [comment]
{"name":"百度","link":"https://www.baidu.com"}

**Comment by jeremyjia** [comment]
{"name":"网易云音乐","link":"https://music.163.com"}

**Comment by jeremyjia** [comment]
{"name":"漂泊者插件管理器","link":"https://jeremyjia.github.io/Games/pbzTools/scriptengine/plugin/pluginCall.html"}

**Comment by jeremyjia** [comment]
{"name":"Javascript chatGTP调用示例","link":"https://www.codeproject.com/Articles/5350454/Chat-GPT-in-JavaScript"}
