### ISSUE TITLE
学习任务：【gdx/test/ 工程】

### ISSUE THREAD

**Issue by littleflute** [jeremyjia/Games#9]
2. 实现：程序运行初始背景为黑色。（先 fork 库，实现后make a Pull request 到源库 ) 
1.【gdx/test/ 工程】编译运行测试（按DeskTop程序方式运行）

请按以下步骤操作

https://jeremyjia.github.io/Games/issues/9/
https://littleflute.github.io/Games/issues/9/

**Comment by littleflute** [comment]
![2](https://user-images.githubusercontent.com/17950965/60234014-73917500-9857-11e9-8093-b722564f341d.png)

**Comment by littleflute** [comment]
![3](https://user-images.githubusercontent.com/17950965/60234016-75f3cf00-9857-11e9-86e1-b34636223034.png)
![4](https://user-images.githubusercontent.com/17950965/60234018-78562900-9857-11e9-97e1-b3d79601f7cd.png)

![5](https://user-images.githubusercontent.com/17950965/60234022-80ae6400-9857-11e9-9f7b-8244370d18a6.png)
![6](https://user-images.githubusercontent.com/17950965/60234030-82782780-9857-11e9-8a79-044973908f8b.png)
![7](https://user-images.githubusercontent.com/17950965/60234044-899f3580-9857-11e9-9985-11cae8f28b17.png)

**Comment by littleflute** [comment]
![4](https://user-images.githubusercontent.com/17950965/60234018-78562900-9857-11e9-97e1-b3d79601f7cd.png)

![5](https://user-images.githubusercontent.com/17950965/60234022-80ae6400-9857-11e9-9f7b-8244370d18a6.png)
![6](https://user-images.githubusercontent.com/17950965/60234030-82782780-9857-11e9-8a79-044973908f8b.png)
![7](https://user-images.githubusercontent.com/17950965/60234044-899f3580-9857-11e9-9985-11cae8f28b17.png)

**Comment by littleflute** [comment]
![5](https://user-images.githubusercontent.com/17950965/60234022-80ae6400-9857-11e9-9f7b-8244370d18a6.png)
![6](https://user-images.githubusercontent.com/17950965/60234030-82782780-9857-11e9-8a79-044973908f8b.png)
![7](https://user-images.githubusercontent.com/17950965/60234044-899f3580-9857-11e9-9985-11cae8f28b17.png)

**Comment by littleflute** [comment]
![6](https://user-images.githubusercontent.com/17950965/60234030-82782780-9857-11e9-8a79-044973908f8b.png)

**Comment by littleflute** [comment]
![7](https://user-images.githubusercontent.com/17950965/60234044-899f3580-9857-11e9-9985-11cae8f28b17.png)

**Comment by littleflute** [comment]
![7](https://user-images.githubusercontent.com/17950965/60234044-899f3580-9857-11e9-9985-11cae8f28b17.png)

**Comment by xiyufeng** [comment]
Done and make a pull request.
After build still has issue in Run tasks step show as "Caused by: com.android.ide.common.signing.KeytoolException: Failed to create keystore." 
That can be ignore since after run project this issue was fixed automatically.

**Comment by littleflute** [comment]
good job.
